import React,{useEffect,useState}from'react';
import{api}from'../api';
import{useLiveReconciliation}from'../live';
import{ConfirmDialog}from'../admin/ConfirmDialog';
type Account={id:string;login_id:string;email?:string|null;role:'admin'|'administration'|'teacher';active:boolean};

export default function AccountsSettings(){
  const[accounts,setAccounts]=useState<Account[]>([]),[selected,setSelected]=useState<Account>(),[adding,setAdding]=useState(false),[message,setMessage]=useState('');
  const load=()=>api('/admin/accounts').then(setAccounts).catch((error:any)=>setMessage(error.message));
  useEffect(()=>{void load()},[]);useLiveReconciliation(load);
  return <section className="accounts-settings"><div className="manager-toolbar"><div><h2>Accounts</h2><p>Email / Account ID is the sign-in identifier. Email is optional; this demo has no outgoing email.</p></div><button onClick={()=>{setAdding(true);setSelected(undefined)}}>+ Add account</button></div><div className="person-list">{accounts.map(account=><button className={`person-row ${account.active?'':'inactive'}`} key={account.id} onClick={()=>{setSelected(account);setAdding(false)}}><span><b>{account.login_id}</b><small>{account.role}</small></span><small>{account.active?'Active':'Inactive'} ›</small></button>)}</div>{adding&&<AccountEditor saved={async()=>{setAdding(false);await load()}}/>}{selected&&<AccountEditor account={selected} saved={async()=>{setSelected(undefined);await load()}}/>}{message&&<p className="error">{message}</p>}</section>;
}

function AccountEditor({account,saved}:{account?:Account;saved:()=>void|Promise<void>}){
  const[email,setEmail]=useState(account?.login_id||''),[role,setRole]=useState<Account['role']>(account?.role||'administration'),[active,setActive]=useState(account?.active??true),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[adminPassword,setAdminPassword]=useState(''),[message,setMessage]=useState(''),[deleting,setDeleting]=useState(false),[confirmDeactivate,setConfirmDeactivate]=useState(false);
  useEffect(()=>{setEmail(account?.login_id||'');setRole(account?.role||'administration');setActive(account?.active??true)},[account?.id]);
  const save=async()=>{try{await api(account?`/admin/accounts/${account.id}`:'/admin/accounts',{method:account?'PATCH':'POST',body:JSON.stringify(account?{email,role,active}:{email,password,role,active})});await saved()}catch(error:any){setMessage(error.message)}};
  const reset=async()=>{try{await api(`/admin/accounts/${account!.id}/password-reset`,{method:'POST',body:JSON.stringify({current_password:adminPassword,new_password:password,confirm_new_password:confirm})});setPassword('');setConfirm('');setAdminPassword('');setMessage('Password reset; existing sessions were signed out.')}catch(error:any){setMessage(error.message)}};
  const destroy=async()=>{try{await api(`/admin/accounts/${account!.id}/delete`,{method:'POST',body:JSON.stringify({admin_password:adminPassword,confirm:email})});await saved()}catch(error:any){setMessage(error.message)}finally{setAdminPassword('');setDeleting(false)}};
  return <article className="manager-editor account-editor"><div className="editor-grid"><label>Email / Account ID<input autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)}/></label>{account?<label>Role<input value={role} disabled/></label>:<label>Role<select value={role} onChange={event=>setRole(event.target.value as Account['role'])}>{['admin','administration','teacher'].map(value=><option key={value}>{value}</option>)}</select></label>}<label className="active-switch">Active<input type="checkbox" role="switch" checked={active} onChange={event=>{if(!event.target.checked&&account?.active){setConfirmDeactivate(true);return}setActive(event.target.checked)}}/><span>{active?'Active':'Inactive'}</span></label>{!account&&<><label>Initial password<input type="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></label></>}</div><button disabled={!email||(!account&&(password.length<8||password!==confirm))} onClick={()=>void save()}>{account?'Save':'Create account'}</button>{account&&<details className="sensitive-action"><summary>Reset password</summary><label>New password<input type="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Confirm new password<input type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></label><label>Current Admin password<input type="password" autoComplete="current-password" value={adminPassword} onChange={event=>setAdminPassword(event.target.value)}/></label><button disabled={password.length<8||password!==confirm||!adminPassword} onClick={()=>void reset()}>Reset password</button></details>} {account&&<button className="danger minor" onClick={()=>setDeleting(true)}>Delete account</button>}{message&&<p role="status">{message}</p>}<ConfirmDialog open={confirmDeactivate} title="Deactivate account?" message="This account will no longer be able to sign in and its existing sessions will be revoked." confirmLabel="Deactivate account" onCancel={()=>setConfirmDeactivate(false)} onConfirm={()=>{setActive(false);setConfirmDeactivate(false)}}/><ConfirmDialog open={deleting} title="Permanently delete account?" message="Historical records will not be cascaded. This is only available for an unused account." confirmLabel="Delete account" disabled={!adminPassword||adminPassword.length<1} onCancel={()=>{setDeleting(false);setAdminPassword('')}} onConfirm={()=>void destroy()}><label>Current Admin password<input autoFocus type="password" autoComplete="current-password" value={adminPassword} onChange={event=>setAdminPassword(event.target.value)}/></label><p>Type the Account ID exactly to confirm permanent deletion.</p></ConfirmDialog></article>;
}
