import React,{useEffect,useState}from'react';
import{api}from'../api';import{listDrafts,removeDraft,saveDraft,sanitizeForLocalStorage}from'../offline';import{ChildSelector}from'./ChildSelector';import{EffectiveTime}from'./EffectiveTime';import{Choice}from'./OrdinaryWorkflows';import{WorkflowWorkspace}from'./WorkflowWorkspace';import{isoOrNow,operationId,type WorkflowProps}from'./types';
const areas=['head','face','neck','chest','back','abdomen','left_arm','right_arm','left_hand','right_hand','left_leg','right_leg','left_foot','right_foot','other'];
export const incidentDraftStorageValue=(value:any)=>sanitizeForLocalStorage(value);
export const incidentActionAt=(effective:string,time:string)=>{if(!time)return null;const day=effective?new Date(effective):new Date();const[hours,minutes]=time.split(':').map(Number);return new Date(day.getFullYear(),day.getMonth(),day.getDate(),hours,minutes).toISOString()};
const fresh=()=>({client_draft_id:operationId('incident-draft'),finalise_operation_id:operationId('incident-final'),incident_id:null,selected:[] as string[],effective:'',implicit_effective_at:new Date().toISOString(),environment:'indoor',location:'',incident_type:'',other_child_id:'',skin_broken:false,description:'',body_areas:[] as string[],actions:[{time:'',description:''}]});
export const incidentDraftMeaningful=(form:any)=>!!(form.selected?.length||form.effective||form.location?.trim()||form.incident_type?.trim()||form.other_child_id||form.skin_broken||form.description?.trim()||form.body_areas?.length||form.actions?.some((x:any)=>x.description?.trim()));
export const incidentServerDrafts=(server:any)=>Array.isArray(server)?server:server?.drafts||[];
export function Incident(props:WorkflowProps){
 const[form,setForm]=useState<any>(fresh),[drafts,setDrafts]=useState<any[]>([]),[pin,setPin]=useState(''),[review,setReview]=useState(false),[ready,setReady]=useState(false),[saving,setSaving]=useState(false);
 const reloadDrafts=async()=>{const local=await listDrafts('incident-draft');const server=await api('/classroom/incidents/drafts').catch(()=>[]);const serverDrafts=Array.isArray(server)?server:server.drafts||[];const merged=[...local.map((x:any)=>x.value),...serverDrafts.filter((x:any)=>!local.some((y:any)=>y.value.client_draft_id===x.client_draft_id)).map((x:any)=>({...fresh(),...x,incident_id:x.id,implicit_effective_at:x.effective_at,selected:[x.child_id],actions:(x.actions||[]).map((a:any)=>({time:a.action_at?new Date(a.action_at).toTimeString().slice(0,5):'',description:a.description}))}))];setDrafts(merged)};
 useEffect(()=>{void reloadDrafts().finally(()=>setReady(true))},[]);
 useEffect(()=>{if(!ready||!incidentDraftMeaningful(form))return;void saveDraft(form.client_draft_id,incidentDraftStorageValue(form));const timer=setTimeout(()=>{if(form.selected.length===1&&navigator.onLine)void api('/classroom/incidents',{method:'POST',body:JSON.stringify(payload(false))}).then((x:any)=>setForm((current:any)=>current.incident_id?current:{...current,incident_id:x.id})).catch(()=>{})},700);return()=>clearTimeout(timer)},[form.client_draft_id,form.selected,form.effective,form.environment,form.location,form.incident_type,form.other_child_id,form.skin_broken,form.description,JSON.stringify(form.body_areas),JSON.stringify(form.actions),ready]);
 const payload=(finalise:boolean)=>({client_draft_id:form.client_draft_id,incident_id:form.incident_id,finalise_operation_id:finalise?form.finalise_operation_id:null,child_id:form.selected[0],room_id:props.roomId,staff_id:props.staffId,effective_at:form.effective?isoOrNow(form.effective):form.implicit_effective_at,environment:form.environment,location:form.location||null,incident_type:form.incident_type,other_child_id:form.other_child_id||null,skin_broken:form.skin_broken,description:form.description||null,body_areas:form.body_areas,actions:form.actions.filter((x:any)=>x.description.trim()).map((x:any)=>({action_at:incidentActionAt(form.effective||form.implicit_effective_at,x.time),description:x.description.trim()})),staff_pin:finalise?pin:null,finalise});
 const discard=async()=>{if(form.incident_id)await api(`/classroom/incidents/drafts/${form.incident_id}`,{method:'DELETE'});await removeDraft(form.client_draft_id);setForm(fresh());setReview(false);await reloadDrafts();await props.refresh();props.notice('Incident draft discarded')};
 const finalise=async()=>{if(form.selected.length!==1||!form.incident_type.trim())return;setSaving(true);try{await api('/classroom/incidents',{method:'POST',body:JSON.stringify(payload(true))});await removeDraft(form.client_draft_id);setPin('');props.notice('Incident finalised');await props.refresh();props.close()}catch(e:any){setPin('');props.notice(navigator.onLine?e.message:'Connection required to verify and finalise. Draft retained.')}finally{setSaving(false)}};
 if(!ready)return <WorkflowWorkspace title="Incident" close={props.close}><p>Recovering drafts…</p></WorkflowWorkspace>;
 const roster=<><ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={form.selected} setSelected={selected=>setForm({...form,selected:selected.slice(-1)})}/>{drafts.length>0&&<section><h3>Saved drafts</h3>{drafts.map((x:any)=><button className="record-row" key={x.client_draft_id} onClick={()=>{setForm(x);setReview(false)}}>{props.data.children.find(c=>c.id===(x.selected?.[0]||x.child_id))?.first_name||'Unassigned'} · {x.incident_type||'Untitled draft'}</button>)}<button className="minor" onClick={()=>{setForm(fresh());setReview(false)}}>+ New incident draft</button></section>}</>;
 const footer=review?<><button className="minor" onClick={()=>setReview(false)}>Back to edit</button><button className="save" disabled={!pin||saving||!navigator.onLine} onClick={finalise}>{saving?'Finalising…':'Verify PIN and finalise once'}</button></>:<><button className="danger minor" onClick={discard}>Discard this draft</button><button className="save" disabled={form.selected.length!==1||!form.incident_type.trim()} onClick={()=>setReview(true)}>Review before finalising</button></>;
 return <WorkflowWorkspace title={review?'Review incident':'Incident / Injury / Illness'} close={props.close} roster={review?undefined:roster} footer={footer}>{!review?<><EffectiveTime value={form.effective} onChange={effective=>setForm({...form,effective})}/><Choice label="Environment" values={['indoor','outdoor']} value={form.environment} set={environment=>setForm({...form,environment})}/>{['location','incident_type','description'].map(key=><label key={key}>{key.replaceAll('_',' ')}{key==='incident_type'&&' (required)'}<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Another child involved<select value={form.other_child_id} onChange={e=>setForm({...form,other_child_id:e.target.value})}><option value="">No / not recorded</option>{props.data.children.filter(c=>!form.selected.includes(c.id)).map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>)}</select></label><label className="check"><input type="checkbox" checked={form.skin_broken} onChange={e=>setForm({...form,skin_broken:e.target.checked})}/> Skin broken / blood</label><fieldset><legend>Body areas (optional)</legend><div className="body-areas">{areas.map(area=><button key={area} className={form.body_areas.includes(area)?'selected':'minor'} onClick={()=>setForm({...form,body_areas:form.body_areas.includes(area)?form.body_areas.filter((x:string)=>x!==area):[...form.body_areas,area]})}>{area.replaceAll('_',' ')}</button>)}</div></fieldset><fieldset><legend>Actions / treatment</legend>{form.actions.map((action:any,index:number)=><div className="inline" key={index}><input aria-label={`Action ${index+1} time`} type="time" value={action.time} onChange={e=>{const actions=[...form.actions];actions[index]={...action,time:e.target.value};setForm({...form,actions})}}/><input aria-label={`Action ${index+1} description`} placeholder="Action" value={action.description} onChange={e=>{const actions=[...form.actions];actions[index]={...action,description:e.target.value};setForm({...form,actions})}}/></div>)}<button className="minor" onClick={()=>setForm({...form,actions:[...form.actions,{time:'',description:''}]})}>+ Another action</button></fieldset></>:<><section className="review"><p><b>Child:</b> {props.data.children.find(c=>c.id===form.selected[0])?.first_name}</p><p><b>Type:</b> {form.incident_type} · {form.environment} {form.location&&`· ${form.location}`}</p><p><b>Areas:</b> {form.body_areas.join(', ')||'Not recorded'}</p><p><b>Description:</b> {form.description||'Not recorded'}</p><p><b>Actions:</b> {form.actions.filter((x:any)=>x.description).map((x:any)=>`${x.time||'time of entry'} ${x.description}`).join(', ')||'None recorded'}</p></section><label>Staff PIN — not saved<input aria-label="Incident staff PIN" type="password" autoComplete="off" value={pin} onChange={e=>setPin(e.target.value)}/></label>{!navigator.onLine&&<p className="error">Connection required. Your draft remains saved.</p>}</>}</WorkflowWorkspace>;
}
