import React,{useEffect,useRef,useState}from'react';
import{api}from'../api';
import{ConfirmDialog}from'../admin/ConfirmDialog';
import{listDrafts,removeDraft,saveDraft,sanitizeForLocalStorage}from'../offline';
import{BodyAreaMap,readableBodyAreas}from'./BodyAreaMap';
import{ChildSelector}from'./ChildSelector';
import{EffectiveTime}from'./EffectiveTime';
import{Choice}from'./OrdinaryWorkflows';
import{WorkflowWorkspace}from'./WorkflowWorkspace';
import{isoOrNow,operationId,type WorkflowProps}from'./types';

export const incidentDraftStorageValue=(value:any)=>sanitizeForLocalStorage(value);
export const incidentActionAt=(effective:string,time:string)=>{if(!time)return null;const day=effective?new Date(effective):new Date();const[hours,minutes]=time.split(':').map(Number);return new Date(day.getFullYear(),day.getMonth(),day.getDate(),hours,minutes).toISOString()};
const fresh=()=>({client_draft_id:operationId('incident-draft'),finalise_operation_id:operationId('incident-final'),incident_id:null,selected:[] as string[],effective:'',implicit_effective_at:new Date().toISOString(),environment:'indoor',location:'',incident_type:'',other_child_id:'',skin_broken:false,description:'',body_areas:[] as string[],actions:[{time:'',description:''}]});
export const incidentDraftMeaningful=(form:any)=>!!(form.selected?.length||form.effective||form.location?.trim()||form.incident_type?.trim()||form.other_child_id||form.skin_broken||form.description?.trim()||form.body_areas?.length||form.actions?.some((x:any)=>x.description?.trim()));
export const incidentServerDrafts=(server:any)=>Array.isArray(server)?server:server?.drafts||[];

export function Incident(props:WorkflowProps){
  const[form,setForm]=useState<any>(fresh),[drafts,setDrafts]=useState<any[]>([]),[pin,setPin]=useState(''),[review,setReview]=useState(false),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[confirmClear,setConfirmClear]=useState(false);
  const clearingRef=useRef(false),autosaveGenerationRef=useRef(0),autosaveRef=useRef<Promise<unknown>>(Promise.resolve()),serverDraftIdRef=useRef<string|null>(null);
  const reloadDrafts=async()=>{const local=await listDrafts('incident-draft');const server=await api('/classroom/incidents/drafts').catch(()=>[]);const serverDrafts=incidentServerDrafts(server);const merged=[...local.map((x:any)=>x.value),...serverDrafts.filter((x:any)=>!local.some((y:any)=>y.value.client_draft_id===x.client_draft_id)).map((x:any)=>({...fresh(),...x,incident_id:x.id,implicit_effective_at:x.effective_at,selected:[x.child_id],actions:(x.actions||[]).map((a:any)=>({time:a.action_at?new Date(a.action_at).toTimeString().slice(0,5):'',description:a.description}))}))];setDrafts(merged)};
  useEffect(()=>{void reloadDrafts().finally(()=>setReady(true))},[]);
  useEffect(()=>{serverDraftIdRef.current=form.incident_id||null},[form.incident_id]);
  const payload=(finalise:boolean)=>({client_draft_id:form.client_draft_id,incident_id:form.incident_id,finalise_operation_id:finalise?form.finalise_operation_id:null,child_id:form.selected[0],room_id:props.roomId,staff_id:props.staffId,effective_at:form.effective?isoOrNow(form.effective):form.implicit_effective_at,environment:form.environment,location:form.location||null,incident_type:form.incident_type,other_child_id:form.other_child_id||null,skin_broken:form.skin_broken,description:form.description||null,body_areas:form.body_areas,actions:form.actions.filter((x:any)=>x.description.trim()).map((x:any)=>({action_at:incidentActionAt(form.effective||form.implicit_effective_at,x.time),description:x.description.trim()})),staff_pin:finalise?pin:null,finalise});
  useEffect(()=>{if(!ready||clearingRef.current||!incidentDraftMeaningful(form))return;const generation=autosaveGenerationRef.current;const current=()=>!clearingRef.current&&generation===autosaveGenerationRef.current;const saveLocal=()=>current()?saveDraft(form.client_draft_id,incidentDraftStorageValue(form)):undefined;autosaveRef.current=autosaveRef.current.then(saveLocal,saveLocal);const timer=setTimeout(()=>{if(!current())return;const saveServer=()=>current()&&form.selected.length===1&&navigator.onLine?api('/classroom/incidents',{method:'POST',body:JSON.stringify(payload(false))}).then((x:any)=>{serverDraftIdRef.current=x.id;setForm((value:any)=>value.incident_id?value:{...value,incident_id:x.id})}):undefined;autosaveRef.current=autosaveRef.current.then(saveServer,saveServer)},700);return()=>clearTimeout(timer)},[form.client_draft_id,form.selected,form.effective,form.environment,form.location,form.incident_type,form.other_child_id,form.skin_broken,form.description,JSON.stringify(form.body_areas),JSON.stringify(form.actions),ready]);
  const startFresh=()=>{serverDraftIdRef.current=null;setForm(fresh());setReview(false)};
  const selectDraft=(draft:any)=>{serverDraftIdRef.current=draft.incident_id||null;setForm(draft);setReview(false)};
  const clearInformation=async()=>{clearingRef.current=true;autosaveGenerationRef.current+=1;try{await autosaveRef.current;const serverDraftId=serverDraftIdRef.current;if(serverDraftId)await api(`/classroom/incidents/drafts/${serverDraftId}`,{method:'DELETE'});await removeDraft(form.client_draft_id);const next=fresh();serverDraftIdRef.current=null;setForm(next);setPin('');setReview(false);await reloadDrafts();await props.refresh();props.notice('Incident information cleared')}catch(error:any){props.notice(error.message)}finally{clearingRef.current=false}};
  const finalise=async()=>{if(form.selected.length!==1||!form.incident_type.trim())return;setSaving(true);try{await api('/classroom/incidents',{method:'POST',body:JSON.stringify(payload(true))});await removeDraft(form.client_draft_id);setPin('');props.notice('Incident finalised');await props.refresh();props.close()}catch(e:any){setPin('');props.notice(navigator.onLine?e.message:'Connection required to verify and finalise. Draft retained.')}finally{setSaving(false)}};
  if(!ready)return <WorkflowWorkspace title="Incident / Injury" helpContext="incident" close={props.close}><p>Recovering drafts…</p></WorkflowWorkspace>;
  const roster=<><ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={form.selected} setSelected={selected=>setForm({...form,selected:selected.slice(-1)})} recentVisitorIds={props.data.recent_visitors?.[props.roomId]}/>{drafts.length>0&&<section><h3>Saved drafts</h3>{drafts.map((x:any)=><button type="button" className="record-row" key={x.client_draft_id} onClick={()=>selectDraft(x)}>{props.data.children.find(c=>c.id===(x.selected?.[0]||x.child_id))?.first_name||'Unassigned'} · {x.incident_type||'Untitled draft'}</button>)}<button type="button" className="minor" onClick={startFresh}>+ New incident draft</button></section>}</>;
  const meaningful=incidentDraftMeaningful(form);
  const footer=review?<><button type="button" className="minor" onClick={()=>setReview(false)}>Back to edit</button><button type="button" className="save" disabled={!pin||saving||!navigator.onLine} onClick={finalise}>{saving?'Finalising…':'Verify PIN and finalise once'}</button></>:<><button type="button" className="danger minor" disabled={!meaningful} onClick={()=>setConfirmClear(true)}>Clear information</button><button type="button" className="save" disabled={form.selected.length!==1||!form.incident_type.trim()} onClick={()=>setReview(true)}>Review before finalising</button></>;
  return <WorkflowWorkspace title={review?'Review incident':'Incident / Injury'} helpContext="incident" close={props.close} roster={review?undefined:roster} footer={footer}>
    {!review?<>
      <EffectiveTime value={form.effective} onChange={effective=>setForm({...form,effective})}/>
      <Choice label="Environment" values={['indoor','outdoor']} value={form.environment} set={environment=>setForm({...form,environment})}/>
      {['location','incident_type','description'].map(key=><label key={key}>{key.replaceAll('_',' ')}{key==='incident_type'&&' (required)'}<input value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}
      <label>Another child involved<select value={form.other_child_id} onChange={event=>setForm({...form,other_child_id:event.target.value})}><option value="">No / not recorded</option>{props.data.children.filter(child=>!form.selected.includes(child.id)).map(child=><option key={child.id} value={child.id}>{child.first_name} {child.last_name}</option>)}</select></label>
      <label className="check"><input type="checkbox" checked={form.skin_broken} onChange={event=>setForm({...form,skin_broken:event.target.checked})}/> Skin broken / blood</label>
      <fieldset><legend>Body areas (optional)</legend><BodyAreaMap value={form.body_areas} onChange={body_areas=>setForm({...form,body_areas})}/></fieldset>
      <fieldset><legend>Actions / treatment</legend>{form.actions.map((action:any,index:number)=><div className="inline" key={index}><input aria-label={`Action ${index+1} time`} type="time" value={action.time} onChange={event=>{const actions=[...form.actions];actions[index]={...action,time:event.target.value};setForm({...form,actions})}}/><input aria-label={`Action ${index+1} description`} placeholder="Action" value={action.description} onChange={event=>{const actions=[...form.actions];actions[index]={...action,description:event.target.value};setForm({...form,actions})}}/></div>)}<button type="button" className="minor" onClick={()=>setForm({...form,actions:[...form.actions,{time:'',description:''}]})}>+ Another action</button></fieldset>
    </>:<><section className="review"><p><b>Child:</b> {props.data.children.find(child=>child.id===form.selected[0])?.first_name}</p><p><b>Type:</b> {form.incident_type} · {form.environment} {form.location&&`· ${form.location}`}</p><p><b>Areas:</b> {readableBodyAreas(form.body_areas)||'Not recorded'}</p><p><b>Description:</b> {form.description||'Not recorded'}</p><p><b>Actions:</b> {form.actions.filter((action:any)=>action.description).map((action:any)=>`${action.time||'time of entry'} ${action.description}`).join(', ')||'None recorded'}</p></section><label>Staff PIN — not saved<input aria-label="Incident staff PIN" type="password" autoComplete="off" value={pin} onChange={event=>setPin(event.target.value)}/></label>{!navigator.onLine&&<p className="error">Connection required. Your draft remains saved.</p>}</>}
    <ConfirmDialog open={confirmClear} title="Clear incident information?" message="This will clear the information entered in this incident. The Incident window will remain open." cancelLabel="Keep information" confirmLabel="Clear information" onCancel={()=>setConfirmClear(false)} onConfirm={()=>{setConfirmClear(false);void clearInformation()}}/>
  </WorkflowWorkspace>;
}
