import React,{useEffect,useRef,useState}from'react';import{api}from'../api';import{Choice}from'./OrdinaryWorkflows';import{WorkflowWorkspace}from'./WorkflowWorkspace';import{operationId,type WorkflowProps}from'./types';
type Medicine={id:string;child_name:string;medication_name:string;dose:string;route:string;scheduled_times:string[];instructions?:string;status:string;received:boolean;receipt_id?:string;returned_at?:string};
export const receiptChecksComplete=(checks:{label:boolean;authority:boolean;expiry:boolean})=>checks.label&&checks.authority&&checks.expiry;
export function Medication(props:WorkflowProps){
 const[items,setItems]=useState<Medicine[]>([]),[selected,setSelected]=useState<Medicine>(),[checks,setChecks]=useState({label:false,authority:false,expiry:false}),[form,setForm]=useState<any>({outcome:'given'}),[pin,setPin]=useState(''),[saving,setSaving]=useState(false);const op=useRef(operationId('medicine'));
 const load=()=>api('/classroom/medications').then(setItems);useEffect(()=>{void load()},[]);const pick=(item:Medicine)=>{op.current=operationId('medicine');setSelected(item);setForm({outcome:'given'});setChecks({label:false,authority:false,expiry:false});setPin('')};
 const receive=async()=>{setSaving(true);try{await api('/medication/receipts',{method:'POST',body:JSON.stringify({authority_id:selected!.id,staff_id:props.staffId,handed_by:form.handed_by,label_checked:checks.label,authority_matched:checks.authority,expiry_checked:checks.expiry,storage_location:form.storage_location,quantity:form.quantity,note:form.note})});props.notice('Medication receipt confirmed');await load();setSelected(undefined);await props.refresh()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}};
 const administer=async()=>{setSaving(true);try{await api('/classroom/medication/administrations',{method:'POST',body:JSON.stringify({client_operation_id:op.current,authority_id:selected!.id,room_id:props.roomId,staff_id:props.staffId,staff_pin:pin,outcome:form.outcome,dose:selected!.dose,note:form.note})});op.current=operationId('medicine');setPin('');props.notice('Medication administration recorded');await load();setSelected(undefined);await props.refresh()}catch(e:any){setPin('');props.notice(e.message)}finally{setSaving(false)}};
 const returned=async()=>{try{await api(`/medication/receipts/${selected!.receipt_id}/return`,{method:'POST',body:JSON.stringify({staff_id:props.staffId,returned_to:form.returned_to})});props.notice('Medication marked returned');await load();setSelected(undefined)}catch(e:any){props.notice(e.message)}};
 if(selected)return <WorkflowWorkspace title={selected.received?'Administer medication':'Receive medication'} close={()=>setSelected(undefined)} footer={<button className="save" disabled={saving||(!selected.received&&!receiptChecksComplete(checks))||(selected.received&&!pin)} onClick={selected.received?administer:receive}>{saving?'Saving…':selected.received?'Verify PIN and record once':'Confirm physical receipt'}</button>}><section className="authority"><h3>{selected.child_name} · {selected.medication_name}</h3><p><b>Dose:</b> {selected.dose} · <b>Route:</b> {selected.route}</p><p><b>Directions:</b> {selected.scheduled_times?.length?selected.scheduled_times.join(', '):'As directed — no automatic due time asserted'}</p><p>{selected.instructions}</p></section>{!selected.received?<>{['label','authority','expiry'].map(key=><Check key={key} label={key==='label'?'Correct label':key==='authority'?'Authority matches':'Expiry checked'} checked={checks[key as keyof typeof checks]} set={value=>setChecks({...checks,[key]:value})}/>)}{['handed_by','storage_location','quantity'].map(key=><label key={key}>{key.replaceAll('_',' ')}<input value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</>:<><Choice label="Outcome" values={['given','refused','partly_taken','spat_out','vomited_afterward','missed','parent_administered','other']} value={form.outcome} set={outcome=>setForm({...form,outcome})}/><label>Staff PIN — required only at final verification<input aria-label="Medication staff PIN" type="password" value={pin} onChange={e=>setPin(e.target.value)} autoComplete="off"/></label><details><summary>Return medicine</summary><label>Returned to<input value={form.returned_to||''} onChange={e=>setForm({...form,returned_to:e.target.value})}/></label><button className="minor" disabled={!form.returned_to} onClick={returned}>Mark returned</button></details></>}<label>Optional note<input value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label></WorkflowWorkspace>;
 return <WorkflowWorkspace title="Medicine" close={props.close}><h3>Awaiting physical receipt</h3>{items.filter(x=>x.status==='authorised'&&!x.received&&!x.returned_at).map(x=><MedicineButton key={x.id} item={x} pick={pick}/>) }<h3>Active authorities</h3><p>These medicines are on site. “Active” does not assert that a dose is currently due.</p>{items.filter(x=>x.received&&!x.returned_at).map(x=><MedicineButton key={x.id} item={x} pick={pick}/>) }<h3>Completed / returned</h3>{items.filter(x=>x.returned_at).map(x=><p key={x.id}>{x.child_name} · {x.medication_name} · returned</p>)}{!items.length&&<p>No medication authorities for this centre.</p>}</WorkflowWorkspace>;
}
function Check({label,checked,set}:{label:string;checked:boolean;set:(value:boolean)=>void}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/>{label}</label>}
function MedicineButton({item,pick}:{item:Medicine;pick:(item:Medicine)=>void}){return <button className="record-row" onClick={()=>pick(item)}><b>{item.child_name}</b><span>{item.medication_name} · {item.dose} · {item.route}</span></button>}
