import React,{useRef,useState}from'react';
import{submitFoodBatch,submitOrdinary}from'../offline';
import{ChildSelector}from'./ChildSelector';
import{EffectiveTime}from'./EffectiveTime';
import{WorkflowWorkspace}from'./WorkflowWorkspace';
import{isoOrNow,operationId,type WorkflowProps}from'./types';

export const foodServingTotal=(servings:number[])=>servings.reduce((sum,value)=>sum+value,0);
export const toiletingReady=(kind:'nappy'|'toilet',form:any)=>kind==='nappy'?Boolean(form.outcome):Boolean(form.what&&form.outcome);
export function createSubmitGate(){let busy=false;return async<T,>(work:()=>Promise<T>)=>{if(busy)return{started:false as const};busy=true;try{return{started:true as const,value:await work()}}finally{busy=false}}}
const amounts=[['None',0],['¼',.25],['½',.5],['¾',.75],['All',1]]as const;

export const stableEffective=(implicit:{current:string|undefined},time:string)=>time?isoOrNow(time):(implicit.current??=new Date().toISOString());
async function submit(props:WorkflowProps,type:string,clientId:string,ids:string[],data:any,effectiveAt:string){if(!ids.length)throw new Error('Choose at least one child.');return submitOrdinary({client_id:clientId,child_ids:ids,type,room_id:props.roomId,performed_by_id:props.staffId,effective_at:effectiveAt,data})}
const selectedText=(ids:string[],props:WorkflowProps)=>ids.length===1?props.data.children.find(c=>c.id===ids[0])?.first_name||'1 selected':`${ids.length} selected`;

export function Toileting({mode='nappy',...props}:WorkflowProps&{mode?:'nappy'|'toilet'}){
  const[selected,setSelected]=useState<string[]>([]),[kind,setKind]=useState<'nappy'|'toilet'>(mode),[form,setForm]=useState<any>({}),[time,setTime]=useState(''),[saving,setSaving]=useState(false);const op=useRef(operationId('toileting')),implicit=useRef<string>();const gate=useRef(createSubmitGate()).current;
  const save=()=>void gate(async()=>{try{setSaving(true);await submit(props,kind,op.current,selected,form,stableEffective(implicit,time));await props.refresh();props.notice(`${kind==='nappy'?'Nappy':'Toilet'} recorded`);props.close()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}});
  const roster=<ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={selected} setSelected={setSelected}/>;
  const footer=<><b>{selectedText(selected,props)}</b><span className="footer-actions"><button className="minor" onClick={props.close}>Cancel</button><button className="save" disabled={saving||!selected.length||!toiletingReady(kind,form)} onClick={save}>{saving?'Saving…':'Save'}</button></span></>;
  return <WorkflowWorkspace title="Toileting" close={props.close} roster={roster} footer={footer}><div className="choices"><button className={kind==='nappy'?'selected':''} onClick={()=>{setKind('nappy');setForm({})}}>Nappy</button><button className={kind==='toilet'?'selected':''} onClick={()=>{setKind('toilet');setForm({})}}>Toilet</button></div>{kind==='nappy'?<><Choice label="Outcome" values={['Dry','Wet','Bowel movement','Wet + bowel movement']} value={form.outcome} set={outcome=>setForm({...form,outcome})}/>{form.outcome?.includes('Bowel')&&<Choice label="Consistency (optional)" values={['hard','normal','soft','runny']} value={form.consistency} set={consistency=>setForm({...form,consistency})}/>}</>:<><Choice label="What" values={['wee','poo','both','tried']} value={form.what} set={what=>setForm({...form,what})}/><Choice label="Outcome" values={['made it','partly made it','accident']} value={form.outcome} set={outcome=>setForm({...form,outcome})}/><label className="check"><input type="checkbox" checked={!!form.clothing_changed} onChange={e=>setForm({...form,clothing_changed:e.target.checked})}/> Clothing changed</label></>}<label>Optional note<input value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><EffectiveTime value={time} onChange={setTime}/></WorkflowWorkspace>;
}

export function Sunscreen(props:WorkflowProps){
  const[selected,setSelected]=useState<string[]>([]),[application,setApplication]=useState('exposed/bare skin'),[note,setNote]=useState(''),[time,setTime]=useState(''),[saving,setSaving]=useState(false);const op=useRef(operationId('sunscreen')),implicit=useRef<string>();const gate=useRef(createSubmitGate()).current;
  const save=()=>void gate(async()=>{try{setSaving(true);const result=await submit(props,'sunscreen',op.current,selected,{application,note},stableEffective(implicit,time));if(!result.queued)await props.refresh();props.notice(result.queued?'Sunscreen saved offline — pending sync':'Sunscreen recorded');props.close()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}});
  const roster=<ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={selected} setSelected={setSelected}/>;
  const footer=<><b>{selectedText(selected,props)}</b><span className="footer-actions"><button className="minor" onClick={props.close}>Cancel</button><button className="save" disabled={saving||!selected.length} onClick={save}>{saving?'Saving…':`Record (${selected.length})`}</button></span></>;
  return <WorkflowWorkspace title="Sunscreen" close={props.close} roster={roster} footer={footer}><Choice label="Application" values={['exposed/bare skin','fuller-body application']} value={application} set={setApplication}/><label>Optional note<input value={note} onChange={e=>setNote(e.target.value)}/></label><EffectiveTime value={time} onChange={setTime}/></WorkflowWorkspace>;
}

type FoodRow={servings:number[];enjoyment:string;override:string};
export function Food(props:WorkflowProps){
  const[selected,setSelected]=useState<string[]>([]),[meal,setMeal]=useState('Lunch'),[description,setDescription]=useState(''),[time,setTime]=useState(''),[rows,setRows]=useState<Record<string,FoodRow>>({}),[saving,setSaving]=useState(false);const op=useRef(operationId('food-batch')),implicit=useRef<string>();const gate=useRef(createSubmitGate()).current;const row=(id:string)=>rows[id]||{servings:[0],enjoyment:'',override:''};const update=(id:string,next:FoodRow)=>setRows(current=>({...current,[id]:next}));
  const save=()=>void gate(async()=>{try{setSaving(true);if(!selected.length)throw new Error('Choose at least one child.');const result=await submitFoodBatch({client_operation_id:op.current,room_id:props.roomId,staff_id:props.staffId,effective_at:stableEffective(implicit,time),meal,description:description.trim()||null,rows:selected.map(id=>{const value=row(id);return{child_id:id,food:value.override.trim()||null,servings:value.servings,total_servings:foodServingTotal(value.servings),enjoyment:value.enjoyment||null}})});if(!result.queued)await props.refresh();props.notice(result.queued?'Food saved offline — pending sync':'Food recorded');props.close()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}});
  const roster=<ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={selected} setSelected={setSelected}/>;
  const footer=<><b>{selectedText(selected,props)}</b><span className="footer-actions"><button className="minor" onClick={props.close}>Cancel</button><button className="save" disabled={saving||!selected.length} onClick={save}>{saving?'Saving…':'Record food'}</button></span></>;
  return <WorkflowWorkspace title="Food" close={props.close} roster={roster} footer={footer}><Choice label="Meal / offering" values={['Morning tea','Lunch','Afternoon tea','Snack','Other']} value={meal} set={setMeal}/><label>Food description <small>(optional)</small><input value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="food-rows">{selected.map(id=>{const child=props.data.children.find(c=>c.id===id)!,value=row(id);return <details className="food-row" key={id} open><summary><b>{child.first_name}</b><span>{foodServingTotal(value.servings)} serving(s)</span></summary><Choice label="Serving" values={amounts.map(x=>x[0])} value={amounts.find(x=>x[1]===value.servings[0])?.[0]} set={label=>update(id,{...value,servings:[amounts.find(x=>x[0]===label)![1],...value.servings.slice(1)]})}/><Choice label="Enjoyment" values={['disliked','neutral','enjoyed']} value={value.enjoyment} set={enjoyment=>update(id,{...value,enjoyment})}/>{value.servings.slice(1).map((amount,index)=><Choice key={index} label={`Extra serving ${index+1}`} values={amounts.map(x=>x[0])} value={amounts.find(x=>x[1]===amount)?.[0]} set={label=>{const servings=[...value.servings];servings[index+1]=amounts.find(x=>x[0]===label)![1];update(id,{...value,servings})}}/>)}<button className="minor" onClick={()=>update(id,{...value,servings:[...value.servings,0]})}>+ serving</button><label>Child-specific food override<input value={value.override} onChange={e=>update(id,{...value,override:e.target.value})}/></label></details>})}</div><EffectiveTime value={time} onChange={setTime}/></WorkflowWorkspace>;
}

export function Workflow({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <WorkflowWorkspace title={title} close={close}>{children}</WorkflowWorkspace>}
export function Choice({label,values,value,set}:{label:string;values:readonly string[];value?:string;set:(value:string)=>void}){return <fieldset><legend>{label}</legend><div className="choices">{values.map(item=><button type="button" key={item} className={value===item?'selected':''} onClick={()=>set(item)}>{item.replaceAll('_',' ')}</button>)}</div></fieldset>}
