import React,{useState}from'react';import{submitOrdinary}from'../offline';import{ChildSelector}from'./ChildSelector';import{EffectiveTime}from'./EffectiveTime';import{isoOrNow,operationId,type WorkflowProps}from'./types';

export const foodServingTotal=(servings:number[])=>servings.reduce((sum,value)=>sum+value,0);
export const toiletingReady=(kind:'nappy'|'toilet',form:any)=>kind==='nappy'?Boolean(form.outcome):Boolean(form.what&&form.outcome);
const amounts=[['None',0],['¼',.25],['½',.5],['¾',.75],['All',1]] as const;
async function submit(props:WorkflowProps,type:string,ids:string[],data:any,time:string){if(!ids.length)throw new Error('Choose at least one child.');return submitOrdinary({client_id:operationId(type),child_ids:ids,type,room_id:props.roomId,performed_by_id:props.staffId,effective_at:isoOrNow(time),data})}

export function Toileting({mode='nappy',...props}:WorkflowProps&{mode?:'nappy'|'toilet'}){const[selected,setSelected]=useState<string[]>([]),[kind,setKind]=useState<'nappy'|'toilet'>(mode),[form,setForm]=useState<any>({}),[time,setTime]=useState(''),[saving,setSaving]=useState(false);const save=async()=>{try{setSaving(true);await submit(props,kind,selected,form,time);props.notice(`${kind==='nappy'?'Nappy':'Toilet'} recorded`);props.close()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}};return <Workflow title="Toileting" close={props.close}><div className="choices"><button className={kind==='nappy'?'selected':''} onClick={()=>{setKind('nappy');setForm({})}}>Nappy</button><button className={kind==='toilet'?'selected':''} onClick={()=>{setKind('toilet');setForm({})}}>Toilet</button></div><ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={selected} setSelected={setSelected}/>{kind==='nappy'?<><Choice label="Outcome" values={['Dry','Wet','Bowel movement','Wet + bowel movement']} value={form.outcome} set={outcome=>setForm({...form,outcome})}/>{form.outcome?.includes('Bowel')&&<Choice label="Consistency" values={['hard','normal','soft','runny']} value={form.consistency} set={consistency=>setForm({...form,consistency})}/>}</>:<><Choice label="What" values={['wee','poo','both','tried']} value={form.what} set={what=>setForm({...form,what})}/><Choice label="Outcome" values={['made it','partly made it','accident']} value={form.outcome} set={outcome=>setForm({...form,outcome})}/><label className="check"><input type="checkbox" checked={!!form.clothing_changed} onChange={e=>setForm({...form,clothing_changed:e.target.checked})}/> Clothing changed</label></>}<label>Optional note<input value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><EffectiveTime value={time} onChange={setTime}/><button className="save" disabled={saving||!selected.length||!toiletingReady(kind,form)} onClick={save}>Save {selected.length||''}</button></Workflow>}

export function Sunscreen(props:WorkflowProps){const[selected,setSelected]=useState<string[]>([]),[application,setApplication]=useState('exposed/bare skin'),[note,setNote]=useState(''),[time,setTime]=useState(''),[saving,setSaving]=useState(false);const save=async()=>{try{setSaving(true);const result=await submit(props,'sunscreen',selected,{application,note},time);props.notice(result.queued?'Sunscreen saved offline — pending sync':'Sunscreen recorded');props.close()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}};return <Workflow title="Sunscreen" close={props.close}><ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={selected} setSelected={setSelected}/><Choice label="Application" values={['exposed/bare skin','fuller-body application']} value={application} set={setApplication}/><label>Optional note<input value={note} onChange={e=>setNote(e.target.value)}/></label><EffectiveTime value={time} onChange={setTime}/><button className="save" disabled={saving||!selected.length} onClick={save}>{saving?'Saving…':`Record sunscreen (${selected.length})`}</button></Workflow>}

export function Food(props:WorkflowProps){const[selected,setSelected]=useState<string[]>([]),[meal,setMeal]=useState('Lunch'),[description,setDescription]=useState(''),[time,setTime]=useState(''),[rows,setRows]=useState<Record<string,{servings:number[];enjoyment:string;override:string}>>({}),[saving,setSaving]=useState(false);const row=(id:string)=>rows[id]||{servings:[0],enjoyment:'',override:''};const update=(id:string,next:any)=>setRows({...rows,[id]:next});const save=async()=>{try{setSaving(true);if(!selected.length)throw new Error('Choose at least one child.');await Promise.all(selected.map(id=>{const r=row(id);return submitOrdinary({client_id:operationId('food'),child_ids:[id],type:'food',room_id:props.roomId,performed_by_id:props.staffId,effective_at:isoOrNow(time),data:{meal,food:r.override||description,servings:r.servings,total_servings:foodServingTotal(r.servings),enjoyment:r.enjoyment||undefined}})}));props.notice('Food recorded');props.close()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}};return <Workflow title="Food" close={props.close}><ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={selected} setSelected={setSelected}/><Choice label="Meal / offering" values={['Morning tea','Lunch','Afternoon tea','Snack','Other']} value={meal} set={setMeal}/><label>Food description<input value={description} onChange={e=>setDescription(e.target.value)}/></label>{selected.map(id=>{const child=props.data.children.find(c=>c.id===id)!,r=row(id);return <section className="per-child" key={id}><h3>{child.first_name} · {foodServingTotal(r.servings)} serving(s)</h3>{r.servings.map((amount,index)=><Choice key={index} label={`Serving ${index+1}`} values={amounts.map(x=>x[0])} value={amounts.find(x=>x[1]===amount)?.[0]} set={label=>{const next=[...r.servings];next[index]=amounts.find(x=>x[0]===label)![1];update(id,{...r,servings:next})}}/>)}<button className="minor" onClick={()=>update(id,{...r,servings:[...r.servings,0]})}>+ Another serving</button><Choice label="Enjoyment (optional)" values={['disliked','neutral','enjoyed']} value={r.enjoyment} set={enjoyment=>update(id,{...r,enjoyment})}/><label>Child-specific food override<input value={r.override} onChange={e=>update(id,{...r,override:e.target.value})}/></label></section>})}<EffectiveTime value={time} onChange={setTime}/><button className="save" disabled={saving||!selected.length||!description} onClick={save}>{saving?'Saving…':'Record food'}</button></Workflow>}

export function Workflow({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="sheet"><section><button aria-label="Close" className="close" onClick={close}>×</button><h2>{title}</h2>{children}</section></div>}
export function Choice({label,values,value,set}:{label:string;values:readonly string[];value?:string;set:(value:string)=>void}){return <fieldset><legend>{label}</legend><div className="choices">{values.map(item=><button type="button" key={item} className={value===item?'selected':''} onClick={()=>set(item)}>{item}</button>)}</div></fieldset>}
