import React,{useEffect,useMemo,useRef,useState}from'react';
import{api}from'../api';import{isPhysicallyInRoom}from'../presence';import{ChildSelector}from'./ChildSelector';import{EffectiveTime}from'./EffectiveTime';import{Choice,stableEffective}from'./OrdinaryWorkflows';import{WorkflowWorkspace}from'./WorkflowWorkspace';import{operationId,type Child,type WorkflowProps}from'./types';
export type SleepSession={id:string;child_id:string;child_name:string;room_id:string;state:'settling'|'sleeping'|'awake_resting';status:'green'|'amber'|'red';last_check_at?:string|null;next_due_at?:string|null;put_down_at?:string|null;fell_asleep_at?:string|null;woke_at?:string|null;stale?:boolean;stale_reason?:string|null;check_interval_minutes:number};
export const sleepCounts=(sessions:SleepSession[],roomId:string)=>({settling:sessions.filter(s=>s.room_id===roomId&&s.state==='settling').length,sleeping:sessions.filter(s=>s.room_id===roomId&&s.state==='sleeping').length,worst:sessions.some(s=>s.room_id===roomId&&s.status==='red')?'red':sessions.some(s=>s.room_id===roomId&&s.status==='amber')?'amber':'green'});
export const sleepingChildIds=(sessions:SleepSession[],roomId:string)=>sessions.filter(s=>s.room_id===roomId&&s.state==='sleeping').map(s=>s.child_id);
export function SleepWorkflow({check=false,initialAction,...props}:WorkflowProps&{check?:boolean;initialAction?:'put_down'|'fell_asleep'|'wake'|'got_up'}){
 const[sessions,setSessions]=useState<SleepSession[]>([]),[selected,setSelected]=useState<string[]>([]),[action,setAction]=useState(check?'check':initialAction||'put_down'),[time,setTime]=useState(''),[note,setNote]=useState(''),[warmth,setWarmth]=useState('normal'),[breathing,setBreathing]=useState('normal'),[wellbeing,setWellbeing]=useState('well'),[saving,setSaving]=useState(false);const op=useRef(operationId(check?'sleep-check':'sleep')),implicit=useRef<string>();
 const load=()=>api('/classroom/sleep-status').then(x=>setSessions(x.sessions));useEffect(()=>{void load()},[]);useEffect(()=>setSelected([]),[action]);
 const byChild=useMemo(()=>Object.fromEntries(sessions.map(s=>[s.child_id,s])),[sessions]);
 const eligible=(child:Child)=>{const s=byChild[child.id];return check?s?.state==='sleeping':action==='put_down'?isPhysicallyInRoom(child,props.roomId)&&!s:action==='fell_asleep'?s?.state==='settling':action==='wake'?s?.state==='sleeping':!!s};
 const reason=(child:Child)=>{const s=byChild[child.id];if(check)return s?'Not currently sleeping':'No active sleep session';if(action==='put_down')return s?`Already ${s.state.replace('_',' ')}`:isPhysicallyInRoom(child,props.roomId)?'Available':'Not physically in this room';if(!s)return'No active sleep session';return `Currently ${s.state.replace('_',' ')}`};
 const state=(child:Child)=>{const s=byChild[child.id];return s?`${s.state.replace('_',' ')}${s.stale?' · stale session':''}`:(child.present?'Awake · present':'Absent')};
 const save=async()=>{if(!selected.length)return;setSaving(true);try{await api('/classroom/sleep',{method:'POST',body:JSON.stringify({client_id:op.current,child_ids:selected,room_id:props.roomId,action,effective_at:stableEffective(implicit,time),staff_id:props.staffId,warmth,breathing,wellbeing,note:note||undefined})});props.notice(check?'Sleep check recorded':`Sleep action recorded: ${action.replace('_',' ')}`);op.current=operationId(check?'sleep-check':'sleep');await props.refresh();props.close()}catch(e:any){props.notice(e.message)}finally{setSaving(false)}};
 const sleeping=sessions.filter(s=>s.room_id===props.roomId&&s.state==='sleeping');
 return <WorkflowWorkspace title={check?'Sleep Check':'Sleep'} close={props.close} roster={<ChildSelector children={props.data.children} rooms={props.data.rooms} roomId={props.roomId} selected={selected} setSelected={setSelected} filter={eligible} eligibilityLabel={reason} stateLabel={state} bulkLabel={check?'Select all sleeping':'Select all eligible present'}/>} footer={<button className="save" disabled={!selected.length||saving} onClick={save}>{saving?'Saving…':check?'Record standard check':`Record ${action.replace('_',' ')}`}</button>}>
  {check?<div className={`sleep-banner ${sleeping.some(s=>s.status==='red')?'red':sleeping.some(s=>s.status==='amber')?'amber':'green'}`}><b>{sleeping.length} sleeping</b> · worst status {sleeping.some(s=>s.status==='red')?'red':sleeping.some(s=>s.status==='amber')?'amber':'green'}</div>:<Choice label="Action" values={['put_down','fell_asleep','wake','got_up']} value={action} set={setAction}/>}
  {check&&<><Choice label="Warmth" values={['normal','warm','cool']} value={warmth} set={setWarmth}/><Choice label="Breathing" values={['normal','changed']} value={breathing} set={setBreathing}/><Choice label="Wellbeing" values={['well','concern']} value={wellbeing} set={setWellbeing}/>{sleeping.map(s=><p key={s.id}><b>{s.child_name}</b> · {s.last_check_at?`last ${new Date(s.last_check_at).toLocaleTimeString()}`:'first check due'} · {s.next_due_at?`next ${new Date(s.next_due_at).toLocaleTimeString()}`:''} · <span className={s.status}>{s.status}</span></p>)}</>}
  {!check&&sessions.filter(s=>s.stale).map(s=><p className="recovered" key={s.id}><b>{s.child_name}</b>: {s.stale_reason}. Select “got up” to reconcile explicitly.</p>)}
  <label>Optional note<input value={note} onChange={e=>setNote(e.target.value)}/></label><EffectiveTime value={time} onChange={setTime}/>
 </WorkflowWorkspace>;
}
