import React,{useEffect,useState}from'react';

const help:Record<string,string[]>={
  presence:['Current Room lists enrolled children; Visiting lists children physically here from another room; Recent lists the latest visitors; remaining Rooms follow.','Mark present creates attendance in this room. Bring into starts a visit, End visit returns to the enrolled room, and Depart centre closes attendance.'],
  toileting:['Select one or more children, then choose Nappy or Toilet and the outcome. An absent child requires confirmation first.','Supply and soiled-clothes alerts remain visible until resolved. Save records each selected child; retryable outages queue ordinary care.'],
  food:['Select children, choose the meal, then record serving, extra servings, enjoyment, and any child-specific override.','Save creates one atomic batch. A retryable outage queues the exact batch without changing the open form.'],
  sunscreen:['Select children and record the application and optional note. Absent children require confirmation.','Save records ordinary care and may queue during a retryable outage.'],
  sleep:['Put down starts settling; Fell asleep records sleep; Wake keeps the session open; Wake and got up closes both stages; Got up closes resting.','Children elsewhere or absent require confirmation. An active sleep in another room can be moved without changing its timestamps or session identity.'],
  'sleep-check':['Only children currently sleeping in this room are selectable. Review due timing, then record warmth, breathing and wellbeing.','Checks require a valid active sleep and preserve the underlying sleep lifecycle.'],
  medicine:['Choose an active authority and verify the acting Teacher. Final administration requires a live connection and PIN confirmation.','Closing Help returns to the unchanged medication workflow; do not share PINs.'],
  incident:['Record the child, time, location, description, body areas and actions. Drafts remain editable until explicit review and PIN finalisation.','Help does not close or discard the draft. Finalisation requires connectivity.'],
  notes:['Review parent notes, mark them read, and pin operationally important items.','Changes reconcile live; notes are not ordinary offline care.'],
  emergency:['This Room includes enrolled children and current visitors, with physical location shown when elsewhere. Whole centre lists every active child once.','Offline or stale warnings mean verify against another source before relying on the roll.'],
  sync:['Ordinary care can queue during retryable outages. Review pending and needs-attention states here.','Medication and incident finalisation remain online-only for safety.']
};
const contextFor=(title:string)=>title==='Attendance / Presence'?'presence':title.toLowerCase().replaceAll(' ','-');

export function WorkflowWorkspace({title,close,roster,children,footer,status,helpContext}:{title:string;close:()=>void|undefined;roster?:React.ReactNode;children:React.ReactNode;footer?:React.ReactNode;status?:React.ReactNode;helpContext?:string}){
 const[showHelp,setShowHelp]=useState(false),context=helpContext||contextFor(title),content=help[context];
 useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target;if(event.key==='?'&&content&&!(target instanceof HTMLElement&&(['INPUT','TEXTAREA','SELECT'].includes(target.tagName)||target.isContentEditable))){event.preventDefault();event.stopImmediatePropagation();setShowHelp(true)}else if(event.key==='Escape'&&showHelp){event.preventDefault();event.stopImmediatePropagation();setShowHelp(false)}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[content,showHelp]);
 return <div className="workflow-workspace" role="dialog" aria-modal="true" aria-label={title}><section className={`workflow-panel ${roster?'':'workflow-single'}`}><header className="workflow-header"><div><h2>{title}</h2>{status}</div><span className="workflow-header-actions">{content&&<button type="button" className="minor workflow-help-trigger" aria-label="Help" title="Help" onClick={()=>setShowHelp(true)}>?</button>}<button type="button" aria-label="Close" className="close" onClick={close}>×</button></span></header><div className="workflow-body">{roster&&<aside className="workflow-roster">{roster}</aside>}<div className="workflow-details">{children}</div></div><footer className="workflow-footer">{footer||<><span/><button type="button" className="minor" onClick={close}>Close</button></>}</footer></section>{showHelp&&<div className="workflow-help" role="dialog" aria-modal="true" aria-label={`${title} help`}><section><header><h2>{title} Help</h2><button className="close" aria-label="Close help" onClick={()=>setShowHelp(false)}>×</button></header>{content.map((paragraph,index)=><p key={index}>{paragraph}</p>)}<button className="minor" onClick={()=>setShowHelp(false)}>Close Help</button></section></div>}</div>;
}
