import React,{useEffect,useRef,useState}from'react';
import{api}from'../api';

export default function AttendanceKiosk(){
  const[data,setData]=useState<any>(),[room,setRoom]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState<any>(),[signer,setSigner]=useState(''),[relationship,setRelationship]=useState(''),[message,setMessage]=useState('');
  const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false);
  const load=()=>api('/classroom/bootstrap').then((boot:any)=>{setData(boot);setRoom(value=>value||boot.default_room_id||boot.rooms[0]?.id||'')}).catch((error:any)=>setMessage(error.message));
  useEffect(()=>{void load()},[]);
  const point=(event:React.PointerEvent<HTMLCanvasElement>)=>{const node=canvas.current!;const box=node.getBoundingClientRect();return{x:(event.clientX-box.left)*node.width/box.width,y:(event.clientY-box.top)*node.height/box.height}};
  const start=(event:React.PointerEvent<HTMLCanvasElement>)=>{drawing.current=true;event.currentTarget.setPointerCapture(event.pointerId);const ctx=canvas.current!.getContext('2d')!;const p=point(event);ctx.beginPath();ctx.moveTo(p.x,p.y)};
  const move=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const ctx=canvas.current!.getContext('2d')!;const p=point(event);ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#17312d';ctx.lineTo(p.x,p.y);ctx.stroke()};
  const clear=()=>canvas.current?.getContext('2d')?.clearRect(0,0,canvas.current.width,canvas.current.height);
  const submit=async()=>{if(!selected||!signer.trim())return;const signature=canvas.current?.toDataURL('image/png')||'';if(signature.length<100){setMessage('Please draw a signature before confirming.');return}try{await api('/attendance/kiosk',{method:'POST',body:JSON.stringify({child_id:selected.id,room_id:room,action:selected.present?'sign_out':'sign_in',signer_name:signer,relationship:relationship||undefined,signature_data:signature})});setSelected(undefined);setSigner('');setRelationship('');clear();setMessage('Attendance recorded.');await load()}catch(error:any){setMessage(error.message)}};
  if(!data)return <main className="loading">Opening attendance…</main>;
  const children=data.children.filter((child:any)=>`${child.first_name} ${child.last_name} ${child.preferred_name||''}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="attendance-kiosk"><header><strong>{data.centre.display_name||'Essentials Marked'}</strong><span>Parent sign-in</span><select value={room} onChange={event=>setRoom(event.target.value)}>{data.rooms.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></header>{!selected?<section><h1>Sign in or sign out</h1><input aria-label="Search children" placeholder="Search children" value={search} onChange={event=>setSearch(event.target.value)}/><div className="person-list">{children.map((child:any)=><button className="presence-row" key={child.id} onClick={()=>setSelected(child)}><span><b>{child.preferred_name||child.first_name} {child.last_name}</b><small>{child.present?'Signed in':'Not signed in'}</small></span><small>{child.present?'Sign out':'Sign in'}</small></button>)}</div></section>:<section className="kiosk-confirm"><button className="minor" onClick={()=>setSelected(undefined)}>← Back</button><h1>{selected.present?'Sign out':'Sign in'} {selected.preferred_name||selected.first_name} {selected.last_name}</h1><label>Your name<input autoFocus value={signer} onChange={event=>setSigner(event.target.value)}/></label><label>Relationship (optional)<input value={relationship} onChange={event=>setRelationship(event.target.value)}/></label><label>Signature<canvas ref={canvas} width="700" height="220" className="signature-pad" onPointerDown={start} onPointerMove={move} onPointerUp={()=>drawing.current=false} onPointerLeave={()=>drawing.current=false}/></label><button className="minor" onClick={clear}>Clear signature</button><button disabled={!signer.trim()} onClick={()=>void submit()}>Confirm {selected.present?'sign out':'sign in'}</button></section>}{message&&<p role="status">{message}</p>}</main>;
}
