"""Explicit initial Essentials Marked schema.

This intentionally describes the schema directly; it must never import current
application metadata. Development databases created by the former prototype
must be reset before using this revision.
"""
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

TABLES = [
"CREATE TABLE centres (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, branch VARCHAR(200), parent_history_days INTEGER NOT NULL DEFAULT 7, timezone VARCHAR(64) NOT NULL DEFAULT 'Pacific/Auckland', sleep_check_minutes INTEGER NOT NULL DEFAULT 10)",
"CREATE TABLE rooms (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), name VARCHAR(100) NOT NULL, accent VARCHAR(20) NOT NULL DEFAULT '#176b5b', icon VARCHAR(40) NOT NULL DEFAULT '🌿')",
"CREATE TABLE staff (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, preferred_name VARCHAR(100), employment_type VARCHAR(40) NOT NULL DEFAULT 'permanent', active BOOLEAN NOT NULL DEFAULT true, pin_hash VARCHAR(255))",
"CREATE TABLE accounts (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL DEFAULT 'admin', active BOOLEAN NOT NULL DEFAULT true)",
"CREATE TABLE children (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), room_id VARCHAR(36) REFERENCES rooms(id), first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL DEFAULT '', preferred_name VARCHAR(100), dob VARCHAR(10), active BOOLEAN NOT NULL DEFAULT true)",
"CREATE TABLE parents (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), name VARCHAR(200) NOT NULL, login VARCHAR(100) NOT NULL UNIQUE, pin_hash VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL DEFAULT true)",
"CREATE TABLE parent_children (id VARCHAR(36) PRIMARY KEY, parent_id VARCHAR(36) NOT NULL REFERENCES parents(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), UNIQUE(parent_id, child_id))",
"CREATE TABLE devices (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), label VARCHAR(120) NOT NULL, default_room_id VARCHAR(36) REFERENCES rooms(id), created_at TIMESTAMP WITH TIME ZONE NOT NULL, last_active_at TIMESTAMP WITH TIME ZONE NOT NULL, revoked BOOLEAN NOT NULL DEFAULT false)",
"CREATE TABLE attendance (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), room_id VARCHAR(36) REFERENCES rooms(id), arrived_at TIMESTAMP WITH TIME ZONE, departed_at TIMESTAMP WITH TIME ZONE, visit_room_id VARCHAR(36) REFERENCES rooms(id), visit_started_at TIMESTAMP WITH TIME ZONE, visit_ended_at TIMESTAMP WITH TIME ZONE)",
"CREATE TABLE events (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), room_id VARCHAR(36) REFERENCES rooms(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), type VARCHAR(40) NOT NULL, visibility VARCHAR(20) NOT NULL DEFAULT 'parent', effective_at TIMESTAMP WITH TIME ZONE NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, performed_by_id VARCHAR(36) REFERENCES staff(id), recorded_by_id VARCHAR(36) REFERENCES staff(id), device_id VARCHAR(36) REFERENCES devices(id), client_id VARCHAR(80) NOT NULL, operation_id VARCHAR(80), data JSON NOT NULL, revision INTEGER NOT NULL DEFAULT 1, finalised BOOLEAN NOT NULL DEFAULT false, UNIQUE(centre_id, client_id))",
"CREATE TABLE pairings (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), room_id VARCHAR(36) REFERENCES rooms(id), token_hash VARCHAR(255) NOT NULL UNIQUE, challenge VARCHAR(6) NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL, consumed_at TIMESTAMP WITH TIME ZONE)",
"CREATE TABLE audits (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), entity VARCHAR(50) NOT NULL, entity_id VARCHAR(36) NOT NULL, action VARCHAR(50) NOT NULL, before JSON, after JSON, actor_id VARCHAR(36), reason TEXT, created_at TIMESTAMP WITH TIME ZONE NOT NULL)",
"CREATE TABLE parent_notes (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), body TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, read_at TIMESTAMP WITH TIME ZONE, pinned BOOLEAN NOT NULL DEFAULT false)",
"CREATE TABLE app_sessions (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), subject_type VARCHAR(20) NOT NULL, subject_id VARCHAR(36) NOT NULL, token_hash VARCHAR(64) NOT NULL UNIQUE, created_at TIMESTAMP WITH TIME ZONE NOT NULL, last_active_at TIMESTAMP WITH TIME ZONE NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL, revoked_at TIMESTAMP WITH TIME ZONE)",
"CREATE TABLE login_attempts (id VARCHAR(36) PRIMARY KEY, scope VARCHAR(30) NOT NULL, key VARCHAR(255) NOT NULL, window_start TIMESTAMP WITH TIME ZONE NOT NULL, count INTEGER NOT NULL DEFAULT 0, UNIQUE(scope,key,window_start))",
"CREATE TABLE sleep_sessions (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), room_id VARCHAR(36) NOT NULL REFERENCES rooms(id), put_down_at TIMESTAMP WITH TIME ZONE NOT NULL, fell_asleep_at TIMESTAMP WITH TIME ZONE, woke_at TIMESTAMP WITH TIME ZONE, got_up_at TIMESTAMP WITH TIME ZONE, quality VARCHAR(40), wake_state VARCHAR(40), wake_reason VARCHAR(100), note TEXT, check_interval_minutes INTEGER NOT NULL DEFAULT 10, opened_by_staff_id VARCHAR(36) NOT NULL REFERENCES staff(id), closed_by_staff_id VARCHAR(36) REFERENCES staff(id), created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL)",
"CREATE TABLE sleep_checks (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), sleep_session_id VARCHAR(36) NOT NULL REFERENCES sleep_sessions(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), room_id VARCHAR(36) NOT NULL REFERENCES rooms(id), checked_at TIMESTAMP WITH TIME ZONE NOT NULL, staff_id VARCHAR(36) NOT NULL REFERENCES staff(id), warmth VARCHAR(40) NOT NULL DEFAULT 'normal', breathing VARCHAR(40) NOT NULL DEFAULT 'normal', wellbeing VARCHAR(40) NOT NULL DEFAULT 'well', note TEXT, created_at TIMESTAMP WITH TIME ZONE NOT NULL)",
"CREATE TABLE medication_authorities (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), medication_name VARCHAR(200) NOT NULL, form VARCHAR(100), concentration VARCHAR(100), dose VARCHAR(100) NOT NULL, route VARCHAR(100) NOT NULL, frequency VARCHAR(200), scheduled_times JSON NOT NULL, starts_on VARCHAR(10), ends_on VARCHAR(10), storage VARCHAR(200), instructions TEXT, category VARCHAR(12) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft', signer_name VARCHAR(200), revision INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL)",
"CREATE TABLE medication_receipts (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), authority_id VARCHAR(36) NOT NULL REFERENCES medication_authorities(id), received_at TIMESTAMP WITH TIME ZONE NOT NULL, handed_by VARCHAR(200), received_by_id VARCHAR(36) NOT NULL REFERENCES staff(id), label_checked BOOLEAN NOT NULL DEFAULT false, authority_matched BOOLEAN NOT NULL DEFAULT false, expiry_checked BOOLEAN NOT NULL DEFAULT false, storage_location VARCHAR(200), quantity VARCHAR(100), note TEXT, returned_at TIMESTAMP WITH TIME ZONE, returned_to VARCHAR(200), returned_by_id VARCHAR(36) REFERENCES staff(id))",
"CREATE TABLE medication_administrations (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), authority_id VARCHAR(36) NOT NULL REFERENCES medication_authorities(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), administered_at TIMESTAMP WITH TIME ZONE NOT NULL, staff_id VARCHAR(36) NOT NULL REFERENCES staff(id), outcome VARCHAR(40) NOT NULL, dose VARCHAR(100) NOT NULL, note TEXT, finalised BOOLEAN NOT NULL DEFAULT true, revision INTEGER NOT NULL DEFAULT 1)",
"CREATE TABLE incidents (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), child_id VARCHAR(36) NOT NULL REFERENCES children(id), room_id VARCHAR(36) NOT NULL REFERENCES rooms(id), effective_at TIMESTAMP WITH TIME ZONE NOT NULL, environment VARCHAR(20), location VARCHAR(200), incident_type VARCHAR(80) NOT NULL, other_child_id VARCHAR(36) REFERENCES children(id), skin_broken BOOLEAN NOT NULL DEFAULT false, description TEXT, status VARCHAR(20) NOT NULL DEFAULT 'draft', revision INTEGER NOT NULL DEFAULT 1, created_by_id VARCHAR(36) NOT NULL REFERENCES staff(id), finalised_by_id VARCHAR(36) REFERENCES staff(id), finalised_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL)",
"CREATE TABLE incident_body_areas (id VARCHAR(36) PRIMARY KEY, incident_id VARCHAR(36) NOT NULL REFERENCES incidents(id), area VARCHAR(40) NOT NULL, UNIQUE(incident_id,area))",
"CREATE TABLE incident_actions (id VARCHAR(36) PRIMARY KEY, incident_id VARCHAR(36) NOT NULL REFERENCES incidents(id), action_at TIMESTAMP WITH TIME ZONE NOT NULL, description TEXT NOT NULL, staff_id VARCHAR(36) NOT NULL REFERENCES staff(id))",
"CREATE TABLE signatures (id VARCHAR(36) PRIMARY KEY, centre_id VARCHAR(36) NOT NULL REFERENCES centres(id), parent_id VARCHAR(36) REFERENCES parents(id), signer_name VARCHAR(200) NOT NULL, relationship VARCHAR(100), domain_type VARCHAR(40) NOT NULL, domain_id VARCHAR(36) NOT NULL, revision INTEGER NOT NULL, purpose VARCHAR(100) NOT NULL, signature_data TEXT NOT NULL, signed_at TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE(domain_type,domain_id,revision,purpose,signer_name))",
]
INDEXES=[
"CREATE INDEX ix_rooms_centre ON rooms(centre_id)","CREATE INDEX ix_children_centre ON children(centre_id)","CREATE INDEX ix_events_centre_type ON events(centre_id,type)","CREATE INDEX ix_events_operation ON events(centre_id,operation_id)","CREATE INDEX ix_sessions_token ON app_sessions(token_hash)","CREATE INDEX ix_sleep_active ON sleep_sessions(centre_id,child_id)","CREATE INDEX ix_medication_authorities_centre ON medication_authorities(centre_id,child_id)","CREATE INDEX ix_incidents_centre ON incidents(centre_id,child_id)"
]
def upgrade():
    for statement in TABLES + INDEXES: op.execute(statement)
def downgrade():
    for name in ('signatures','incident_actions','incident_body_areas','incidents','medication_administrations','medication_receipts','medication_authorities','sleep_checks','sleep_sessions','login_attempts','app_sessions','parent_notes','audits','pairings','events','attendance','devices','parent_children','parents','children','accounts','staff','rooms','centres'): op.execute(f'DROP TABLE {name}')
