import React,{useEffect,useMemo,useState}from'react';
import{api}from'../api';

type Family={id:string;name:string;login:string;active:boolean;children:{id:string;name:string;first_name?:string;last_name?:string;preferred_name?:string;enrolled_room?:string}[]};
export const familyMatches=(item:Family,search:string)=>`${item.name} ${item.login} ${item.children.map(child=>[child.name,child.first_name,child.last_name,child.preferred_name,child.enrolled_room].filter(Boolean).join(' ')).join(' ')}`.toLowerCase().includes(search.toLowerCase());

export default function FamiliesManager({children,notice}:{children:any[];notice:(value:string)=>void}){
  const[items,setItems]=useState<Family[]>([]);const[search,setSearch]=useState('');const[adding,setAdding]=useState(false);const[editing,setEditing]=useState<Family>();
  const load=()=>api('/admin/families').then(setItems).catch((error:any)=>notice(error.message));
  useEffect(()=>{void load()},[]);
  const shown=useMemo(()=>items.filter(item=>familyMatches(item,search)),[items,search]);
  return <section><div className="manager-toolbar"><div><h2>Families</h2><p>Parent logins are independent of email delivery.</p></div><div className="inline-actions"><input className="manager-search" aria-label="Search families" placeholder="Search families…" value={search} onChange={event=>setSearch(event.target.value)}/><button onClick={()=>{setAdding(true);setEditing(undefined)}}>+ Add family</button></div></div>{adding&&<FamilyEditor children={children} saved={async()=>{setAdding(false);await load()}} notice={notice}/>}<div className="person-list">{shown.map(item=><React.Fragment key={item.id}><button className={`person-row ${item.active?'':'inactive'}`} onClick={()=>{setEditing(editing?.id===item.id?undefined:item);setAdding(false)}}><span><b>{item.name}</b><small>{item.login} · {item.children.map(child=>child.name).join(', ')||'No linked children'}</small></span><small>{item.active?'Active':'Inactive'}</small></button>{editing?.id===item.id&&<FamilyEditor family={item} children={children} saved={load} notice={notice}/>}</React.Fragment>)}</div></section>;
}

function FamilyEditor({family,children,saved,notice}:{family?:Family;children:any[];saved:()=>void|Promise<void>;notice:(value:string)=>void}){
  const[name,setName]=useState(family?.name||'');const[login,setLogin]=useState(family?.login||'');const[active,setActive]=useState(family?.active??true);const[ids,setIds]=useState<string[]>(family?.children.map(child=>child.id)||[]);const[pin,setPin]=useState('');const[accountPassword,setAccountPassword]=useState('');
  const save=async()=>{try{const body={name,login,active,child_ids:ids,...(!family?{pin}: {})};await api(family?`/admin/families/${family.id}`:'/admin/families',{method:family?'PATCH':'POST',body:JSON.stringify(body)});await saved();notice(family?'Family updated':'Family added')}catch(error:any){notice(error.message)}};
  const reset=async()=>{try{await api(`/admin/families/${family!.id}/pin-reset`,{method:'POST',body:JSON.stringify({pin,account_password:accountPassword})});setPin('');setAccountPassword('');notice('Family PIN reset')}catch(error:any){notice(error.message)}};
  return <article className="manager-editor family-editor"><div className="family-section editor-grid"><label>Name<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Login<input value={login} onChange={event=>setLogin(event.target.value)}/></label><label className="check">Status<input type="checkbox" checked={active} onChange={event=>setActive(event.target.checked)}/> Active</label>{!family&&<label>Initial 6-digit PIN<input inputMode="numeric" value={pin} maxLength={6} onChange={event=>setPin(event.target.value.replace(/\D/g,''))}/></label>}</div><fieldset className="family-children"><legend>Linked children</legend>{children.map(child=><label className="check" key={child.id}><input type="checkbox" checked={ids.includes(child.id)} onChange={()=>setIds(ids.includes(child.id)?ids.filter(id=>id!==child.id):[...ids,child.id])}/>{child.preferred_name||child.first_name} {child.last_name}</label>)}</fieldset><div className="inline-actions"><button disabled={!name.trim()||!login.trim()||(!family&&pin.length!==6)} onClick={()=>void save()}>{family?'Save family':'Create family'}</button>{family&&<details className="family-sensitive"><summary>Reset six-digit PIN</summary><label>New PIN<input inputMode="numeric" value={pin} maxLength={6} onChange={event=>setPin(event.target.value.replace(/\D/g,''))}/></label><label>Your account password<input type="password" value={accountPassword} onChange={event=>setAccountPassword(event.target.value)}/></label><button disabled={pin.length!==6||!accountPassword} onClick={()=>void reset()}>Reset PIN</button></details>}</div></article>;
}
