import React,{useMemo,useState}from'react';
import{api}from'../api';
import AccountPassword from'../account/AccountPassword';
import AccountsSettings from'../account/AccountsSettings';
import{ConfirmDialog}from'./ConfirmDialog';

const timezoneNames:Record<string,string>={'Pacific/Auckland':'Auckland, New Zealand','Pacific/Chatham':'Chatham Islands, New Zealand','Australia/Sydney':'Sydney, Australia','Australia/Melbourne':'Melbourne, Australia','Pacific/Fiji':'Fiji','UTC':'UTC'};
export const timezoneOffset=(zone:string,at=new Date())=>{const raw=new Intl.DateTimeFormat('en-NZ',{timeZone:zone,timeZoneName:'longOffset'}).formatToParts(at).find(part=>part.type==='timeZoneName')?.value||'GMT';const match=/GMT([+-])(\d{1,2})(?::(\d{2}))?/.exec(raw);return match?`UTC${match[1]}${String(match[2]).padStart(2,'0')}:${match[3]||'00'}`:'UTC+00:00'};
export const centreTimezoneOptions=(current='Pacific/Auckland')=>{const fallback=['Pacific/Auckland','Pacific/Chatham','Australia/Sydney','Australia/Melbourne','Pacific/Fiji','UTC'];const supported=typeof(Intl as any).supportedValuesOf==='function'?(Intl as any).supportedValuesOf('timeZone') as string[]:fallback;return [...new Set([current,'Pacific/Auckland',...supported])].map(value=>({value,label:`${timezoneNames[value]||value.split('/').reverse().join(', ').replaceAll('_',' ')} — ${timezoneOffset(value)}`}));};

function SettingsPanel({title,children,lazy=false}:{title:string;children:React.ReactNode;lazy?:boolean}){const[mounted,setMounted]=useState(!lazy);return <details className="settings-panel" onToggle={event=>{if(event.currentTarget.open)setMounted(true)}}><summary>{title}</summary><div className="settings-panel-body">{mounted&&children}</div></details>}

export function SettingsPage({data,isAdmin,saved}:{data:any;isAdmin:boolean;saved:()=>void|Promise<void>}){
  const[displayName,setName]=useState(data.centre.display_name||''),[secondaryText,setSecondary]=useState(data.centre.secondary_text||''),[timezone,setTimezone]=useState(data.centre.timezone||'Pacific/Auckland'),[logo,setLogo]=useState(data.centre.logo_url),[busy,setBusy]=useState(false),[confirmBranding,setConfirmBranding]=useState(false);
  const[printSettings,setPrintSettings]=useState(data.centre.emergency_print||{columns:3,sort:'room_then_name',show_room:true,orientation:'portrait',name_size:'standard'});
  const[operations,setOperations]=useState({parent_history_days:data.centre.parent_history_days||7,sleep_check_minutes:data.centre.sleep_check_minutes||10,attendance_relationship_required:data.centre.attendance_relationship_required!==false});
  const timezones=useMemo(()=>centreTimezoneOptions(timezone),[timezone]);
  const upload=async(file:File)=>{setBusy(true);try{const body=new FormData();body.append('file',file);const response=await fetch('/api/admin/branding/logo',{method:'POST',credentials:'include',body});if(!response.ok)throw new Error((await response.json()).detail||'Logo upload failed');const result=await response.json();setLogo(`${result.logo_url}?v=${Date.now()}`);await saved()}finally{setBusy(false)}};
  return <section className="settings-panels">
    <SettingsPanel title="My sign-in"><AccountPassword embedded/></SettingsPanel>
    {isAdmin&&<>
      <SettingsPanel title="Accounts" lazy><AccountsSettings/></SettingsPanel>
      <SettingsPanel title="Centre & branding"><form className="settings-grid" onSubmit={event=>{event.preventDefault();setConfirmBranding(true)}}><label>Display name<input value={displayName} onChange={event=>setName(event.target.value)}/></label><label>Secondary text<input value={secondaryText} onChange={event=>setSecondary(event.target.value)}/></label><div className="settings-action"><button>Save centre &amp; branding</button></div></form><ConfirmDialog open={confirmBranding} title="Apply branding changes?" message="Apply these branding changes to the centre?" confirmLabel="Apply branding" onCancel={()=>setConfirmBranding(false)} onConfirm={()=>{setConfirmBranding(false);void api('/admin/branding',{method:'PATCH',body:JSON.stringify({display_name:displayName,secondary_text:secondaryText})}).then(saved)}}/><div className="logo-settings">{logo&&<img className="branding-preview" src={logo} alt="Current centre logo"/>}<label>Logo — PNG, JPEG, or WebP<input aria-label="Upload centre logo" disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/></label>{logo&&<button type="button" className="danger minor" onClick={()=>void api('/admin/branding/logo',{method:'DELETE'}).then(()=>{setLogo(null);return saved()})}>Remove logo</button>}</div></SettingsPanel>
      <SettingsPanel title="Centre timezone"><form className="settings-grid timezone-settings" onSubmit={event=>{event.preventDefault();void api('/admin/branding',{method:'PATCH',body:JSON.stringify({timezone})}).then(saved)}}><label>Centre timezone<select aria-label="Centre timezone" value={timezone} onChange={event=>setTimezone(event.target.value)}>{timezones.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><small>{timezone} · {timezoneOffset(timezone)}. Times throughout the system use this centre timezone.</small></label><div className="settings-action"><button>Save timezone</button></div></form></SettingsPanel>
      <SettingsPanel title="Parent experience"><form className="settings-grid" onSubmit={event=>{event.preventDefault();void api('/admin/operational-settings',{method:'PATCH',body:JSON.stringify(operations)}).then(saved)}}><label>Parent history window<select value={operations.parent_history_days} onChange={event=>setOperations({...operations,parent_history_days:Number(event.target.value)})}>{[7,14,30,60,90].map(days=><option value={days} key={days}>{days} days</option>)}</select><small>How far back families can view records online.</small></label><label className="active-switch">Require relationship on Parent sign-in<input type="checkbox" role="switch" checked={operations.attendance_relationship_required} onChange={event=>setOperations({...operations,attendance_relationship_required:event.target.checked})}/><span>{operations.attendance_relationship_required?'Required':'Optional'}</span></label><div className="settings-action"><button>Save Parent settings</button></div></form></SettingsPanel>
      <SettingsPanel title="Sleep & care"><form className="settings-grid" onSubmit={event=>{event.preventDefault();void api('/admin/operational-settings',{method:'PATCH',body:JSON.stringify(operations)}).then(saved)}}><label>Sleep check interval<select value={operations.sleep_check_minutes} onChange={event=>setOperations({...operations,sleep_check_minutes:Number(event.target.value)})}>{[5,6,7,8,9,10].map(minutes=><option value={minutes} key={minutes}>{minutes} minutes</option>)}</select><small>Safety checks must remain between 5 and 10 minutes.</small></label><div className="settings-action"><button>Save Sleep settings</button></div></form></SettingsPanel>
      <SettingsPanel title="Emergency roll / printing"><form onSubmit={event=>{event.preventDefault();void api('/admin/emergency-print-settings',{method:'PATCH',body:JSON.stringify(printSettings)}).then(saved)}}><div className="emergency-settings-grid"><label>Columns<select value={printSettings.columns} onChange={event=>setPrintSettings({...printSettings,columns:Number(event.target.value)})}><option value={2}>2</option><option value={3}>3</option></select></label><label>Sort<select value={printSettings.sort} onChange={event=>setPrintSettings({...printSettings,sort:event.target.value})}><option value="alphabetical">Alphabetical</option><option value="room_then_name">Room then name</option></select></label><label>Orientation<select value={printSettings.orientation} onChange={event=>setPrintSettings({...printSettings,orientation:event.target.value})}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label>Name size<select value={printSettings.name_size} onChange={event=>setPrintSettings({...printSettings,name_size:event.target.value})}><option value="standard">Standard</option><option value="large">Large</option></select></label></div><label className="active-switch emergency-room-toggle">Show room names on printed roll<input type="checkbox" role="switch" checked={printSettings.show_room} onChange={event=>setPrintSettings({...printSettings,show_room:event.target.checked})}/><span>{printSettings.show_room?'On':'Off'}</span></label><button>Save print settings</button></form></SettingsPanel>
    </>}
  </section>;
}

export function Branding({data,saved}:{data:any;saved:()=>void|Promise<void>}){return <SettingsPage data={data} isAdmin saved={saved}/>}
