// @vitest-environment jsdom
import React from'react';
import{act}from'react';
import{createRoot}from'react-dom/client';
import{afterEach,describe,expect,it,vi}from'vitest';
import AttendanceKiosk from'./attendance/AttendanceKiosk';
import ActivityLog from'./admin/ActivityLog';
import{FullscreenToggle}from'./FullscreenToggle';
import{Toileting}from'./classroom/OrdinaryWorkflows';
import{SleepWorkflow,nextSleepActionForChild,sleepActionTone,sleepStateTone,type SleepSession}from'./classroom/Sleep';
import{WorkflowWorkspace}from'./classroom/WorkflowWorkspace';

(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
const json=(value:any)=>new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});
const rooms=[{id:'room',name:'Harakeke',accent:'#176b5b',icon:'🌿'}];
const children=[{id:'mila',first_name:'Mila',last_name:'Chen',room_id:'room',present:true},{id:'theo',first_name:'Theo',last_name:'Banks',room_id:'room',present:true}];
const workflow:any={data:{device_id:'d',default_room_id:'room',rooms,staff:[{id:'staff',name:'Sarah'}],children,unread_notes:0,recent_visitors:{}},roomId:'room',staffId:'staff',refresh:async()=>{},notice:()=>{}};
afterEach(()=>{document.body.innerHTML='';vi.unstubAllGlobals();vi.useRealTimers();Object.defineProperty(document,'fullscreenElement',{configurable:true,value:null})});

describe('sleep workflow cohesion',()=>{
  const session=(state:SleepSession['state'],extra:Partial<SleepSession>={}):SleepSession=>({id:'s',child_id:'mila',child_name:'Mila Chen',room_id:'room',state,status:'green',check_interval_minutes:10,...extra});
  it('maps every lifecycle state to the safe next action',()=>{expect(nextSleepActionForChild()).toBe('put_down');expect(nextSleepActionForChild(session('settling'))).toBe('fell_asleep');expect(nextSleepActionForChild(session('sleeping'))).toBe('wake');expect(nextSleepActionForChild(session('awake_resting'))).toBe('got_up');expect(nextSleepActionForChild(session('sleeping',{stale:true}))).toBe('got_up')});
  it('provides semantic state and action classes',()=>{expect(sleepStateTone(session('settling'))).toBe('sleep-state-settling');expect(sleepStateTone(session('sleeping'))).toBe('sleep-state-sleeping');expect(sleepStateTone(session('awake_resting'))).toBe('sleep-state-awake_resting');expect(sleepStateTone(session('sleeping',{stale:true}))).toBe('sleep-state-stale');expect(sleepActionTone('wake_and_got_up')).toBe('sleep-action-wake-and-got-up')});
  it('infers from only the first child, preserves selection, and permits manual changes',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>json({sessions:[session('settling'),{...session('settling'),id:'s2',child_id:'theo',child_name:'Theo Banks'}]})));const host=document.createElement('div');document.body.append(host);await act(async()=>{createRoot(host).render(<SleepWorkflow {...workflow} close={()=>{}}/>);await Promise.resolve();await Promise.resolve()});const childButtons=[...host.querySelectorAll('.child-roster button')]as HTMLButtonElement[];await act(async()=>childButtons.find(button=>button.textContent?.includes('Mila'))!.click());expect(childButtons.find(button=>button.textContent?.includes('Mila'))!.classList.contains('selected')).toBe(true);expect([...host.querySelectorAll('.choices button')].find(button=>button.textContent==='fell asleep')?.classList.contains('selected')).toBe(true);await act(async()=>childButtons.find(button=>button.textContent?.includes('Theo'))!.click());expect([...host.querySelectorAll('.choices button')].find(button=>button.textContent==='fell asleep')?.classList.contains('selected')).toBe(true);await act(async()=>{([...host.querySelectorAll('.choices button')].find(button=>button.textContent==='got up')as HTMLButtonElement).click()});expect([...host.querySelectorAll('.choices button')].find(button=>button.textContent==='got up')?.classList.contains('selected')).toBe(true);expect(host.querySelectorAll('.child-roster button.selected')).toHaveLength(0)});
});

describe('fullscreen and close contracts',()=>{
  it('tracks request, exit, browser/Escape changes, and rejected requests',async()=>{let fullscreen:any=null;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen});const request=vi.fn(async()=>{fullscreen=document.documentElement});const exit=vi.fn(async()=>{fullscreen=null});Object.defineProperty(document.documentElement,'requestFullscreen',{configurable:true,value:request});Object.defineProperty(document,'exitFullscreen',{configurable:true,value:exit});const host=document.createElement('div');document.body.append(host);await act(async()=>createRoot(host).render(<FullscreenToggle/>));let button=host.querySelector('button')!;expect(button.textContent).toContain('Full screen');await act(async()=>{button.click();await Promise.resolve();document.dispatchEvent(new Event('fullscreenchange'))});button=host.querySelector('button')!;expect(request).toHaveBeenCalledOnce();expect(button.textContent).toBe('Exit full screen');expect(button.classList.contains('fullscreen-exit')).toBe(true);await act(async()=>{button.click();await Promise.resolve();document.dispatchEvent(new Event('fullscreenchange'))});expect(exit).toHaveBeenCalledOnce();fullscreen=document.documentElement;await act(async()=>document.dispatchEvent(new Event('fullscreenchange')));fullscreen=null;await act(async()=>document.dispatchEvent(new Event('fullscreenchange')));expect(host.textContent).toContain('Full screen');request.mockRejectedValueOnce(new Error('denied'));await act(async()=>{host.querySelector('button')!.dispatchEvent(new MouseEvent('click',{bubbles:true}));await Promise.resolve()});expect(host.textContent).toContain('Full screen')});
  it('shows Child sign-in wording and the shared fullscreen control',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>json({centre:{display_name:'Demo',timezone:'Pacific/Auckland'},assigned_room:rooms[0],default_room_id:'room',children:[]})));const host=document.createElement('div');document.body.append(host);await act(async()=>{createRoot(host).render(<AttendanceKiosk/>);await Promise.resolve();await Promise.resolve()});expect(host.textContent).toContain('Child sign-in · Harakeke');expect(host.textContent).toContain('Full screen');expect(host.textContent).not.toContain('Parent sign-in')});
  it('uses one Toileting close callback from the header and footer',async()=>{const close=vi.fn(),host=document.createElement('div');document.body.append(host);const root=createRoot(host);await act(async()=>root.render(<Toileting {...workflow} close={close}/>));await act(async()=>{(host.querySelector('[aria-label="Close"]')as HTMLButtonElement).click()});expect(close).toHaveBeenCalledOnce();close.mockClear();await act(async()=>root.render(<Toileting {...workflow} close={close}/>));await act(async()=>{([...host.querySelectorAll('button')].find(button=>button.textContent==='Cancel')as HTMLButtonElement).click()});expect(close).toHaveBeenCalledOnce()});
  it('closes Help before the underlying workflow',async()=>{const close=vi.fn(),host=document.createElement('div');document.body.append(host);await act(async()=>createRoot(host).render(<WorkflowWorkspace title="Toileting" close={close}><span>Form</span></WorkflowWorkspace>));await act(async()=>{(host.querySelector('[aria-label="Help"]')as HTMLButtonElement).click()});await act(async()=>{(host.querySelector('[aria-label="Close help"]')as HTMLButtonElement).click()});expect(close).not.toHaveBeenCalled();expect(host.querySelector('[aria-label="Toileting help"]')).toBeNull()});
});

describe('Activity note presentation and privileged reveal',()=>{
  const parent={id:'p',source:'parent_note',type:'parent_note',activity:'Parent note',child_name:'Mila Chen',effective_at:'2026-09-11T02:15:00Z',recorded_at:'2026-09-11T02:15:00Z',data:{body:'Please give Mila some bacon.'}};
  const teacher={id:'t',source:'event',type:'staff_note',activity:'Teacher note',child_name:'Mila Chen',teacher:'Sarah T.',room:'Harakeke',effective_at:'2026-09-11T02:30:00Z',recorded_at:'2026-09-11T02:30:00Z',data:{note:'Seemed tired after lunch.'}};
  const data={centre:{timezone:'Pacific/Auckland'},children:[],rooms:[],staff:[]};
  async function renderLog(isAdmin:boolean,item:any,urls:string[]){vi.useFakeTimers();vi.stubGlobal('EventSource',class{addEventListener(){}close(){}});vi.stubGlobal('fetch',vi.fn(async(url:any)=>{urls.push(String(url));return String(url).includes('/original')?json({body:'give this kid some bacon'}):json({items:[item]})}));const host=document.createElement('div');document.body.append(host);await act(async()=>createRoot(host).render(<ActivityLog data={data} isAdmin={isAdmin} notice={()=>{}}/>));await act(async()=>vi.advanceTimersByTimeAsync(300));await act(async()=>{(host.querySelector('.person-row')as HTMLButtonElement).click()});return host}
  it('shows softened Parent text immediately and lazily reveals audited original inline for Admin',async()=>{const urls:string[]=[];const host=await renderLog(true,parent,urls);expect(host.textContent).toContain('Please give Mila some bacon.');expect(urls.some(url=>url.includes('/original'))).toBe(false);expect(host.textContent).not.toContain('View original');const details=host.querySelector('.activity-detail details')as HTMLDetailsElement;details.open=true;await act(async()=>{details.dispatchEvent(new Event('toggle'));await Promise.resolve();await Promise.resolve()});expect(urls.some(url=>url.includes('/admin/parent-notes/p/original'))).toBe(true);expect(host.textContent).toContain('give this kid some bacon');expect(host.querySelector('.modal-backdrop')).toBeNull()});
  it('shows Teacher note text directly without raw JSON',async()=>{const host=await renderLog(false,teacher,[]);expect(host.textContent).toContain('Seemed tired after lunch.');expect(host.querySelector('.activity-detail pre')).toBeNull()});
  it('never requests or reveals original Parent text for non-Admin',async()=>{const urls:string[]=[];const host=await renderLog(false,parent,urls);const details=host.querySelector('.activity-detail details')as HTMLDetailsElement;details.open=true;await act(async()=>details.dispatchEvent(new Event('toggle')));expect(urls.some(url=>url.includes('/original'))).toBe(false);expect(host.textContent).not.toContain('give this kid some bacon')});
});
