// @vitest-environment jsdom
import React from'react';import{act}from'react';import{createRoot}from'react-dom/client';import{afterEach,describe,expect,it,vi}from'vitest';import{ChildSelector}from'./classroom/ChildSelector';import{incidentActionAt,incidentDraftMeaningful,incidentServerDrafts}from'./classroom/Incident';import{WorkflowWorkspace}from'./classroom/WorkflowWorkspace';import{Presence}from'./classroom/Presence';import{stableEffective}from'./classroom/OrdinaryWorkflows';import{canRequestOlderRecord}from'./parent/Parent';import{outboxDelivery}from'./offline';
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
const rooms=[{id:'room-a',name:'Kōwhai',accent:'#000',icon:'leaf'}];const children=[{id:'present',first_name:'Mila',last_name:'Chen',room_id:'room-a',present:true},{id:'absent',first_name:'Ava',last_name:'Patel',room_id:'room-a',present:false}];
afterEach(()=>{document.body.innerHTML='';vi.unstubAllGlobals();vi.useRealTimers()});
describe('classroom workflow components',()=>{
 it('keeps ineligible roster children visible but disabled',async()=>{const host=document.createElement('div');document.body.append(host);await act(async()=>createRoot(host).render(<ChildSelector children={children} rooms={rooms} roomId="room-a" selected={[]} setSelected={()=>{}} filter={child=>!!child.present} eligibilityLabel={()=>"Not physically in this room"}/>));const buttons=[...host.querySelectorAll('button')];expect(buttons.some(x=>x.textContent?.includes('Mila'))).toBe(true);const absent=buttons.find(x=>x.textContent?.includes('Ava'))!;expect(absent.getAttribute('aria-disabled')).toBe('true');expect(absent.textContent).toContain('Not physically in this room')});
 it('combines an action time with the incident local day',()=>{const value=incidentActionAt('2026-08-29T09:00:00+12:00','14:35');expect(value).toContain('T02:35:00.000Z')});
});
describe('convergence contracts',()=>{
 it('renders the documented panel structure and single-pane class',async()=>{const host=document.createElement('div');document.body.append(host);const root=createRoot(host);await act(async()=>root.render(<WorkflowWorkspace title="With roster" close={()=>{}} roster={<span>Roster</span>}><span>Details</span></WorkflowWorkspace>));expect(host.querySelector('.workflow-workspace>.workflow-panel')).toBeTruthy();expect(host.querySelector('.sheet')).toBeNull();await act(async()=>root.render(<WorkflowWorkspace title="Single" close={()=>{}}><span>Details</span></WorkflowWorkspace>));expect(host.querySelector('.workflow-panel')?.classList.contains('workflow-single')).toBe(true)});
 it('parses the server array contract and does not treat an untouched incident as meaningful',()=>{const row={id:'draft-1'};expect(incidentServerDrafts([row])).toEqual([row]);expect(incidentDraftMeaningful({selected:[],effective:'',location:'',incident_type:'',other_child_id:'',skin_broken:false,description:'',body_areas:[],actions:[{description:''}]})).toBe(false);expect(incidentDraftMeaningful({selected:['child']})).toBe(true)});
 it('retains one implicit timestamp for retries and routes food outbox envelopes to the batch API',()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-08-29T00:00:00Z'));const ref:{current:string|undefined}={current:undefined};const first=stableEffective(ref,'');vi.setSystemTime(new Date('2026-08-29T00:05:00Z'));expect(stableEffective(ref,'')).toBe(first);const payload={client_operation_id:'food-1'};expect(outboxDelivery({kind:'food_batch',payload}).path).toBe('/api/classroom/food-batch');expect(outboxDelivery({kind:'food_batch',payload}).payload).toBe(payload)});
 it('offers older-record requests only for the history-window response',()=>{expect(canRequestOlderRecord(403,'This date is outside the family history window')).toBe(true);expect(canRequestOlderRecord(500,'Server unavailable')).toBe(false);expect(canRequestOlderRecord(401,'Sign in')).toBe(false)});
 it('sends the selected acting staff in attendance requests',async()=>{let body:any;vi.stubGlobal('fetch',vi.fn(async(_url:any,init:any)=>{body=JSON.parse(init.body);return new Response(JSON.stringify({ok:true}),{status:200,headers:{'Content-Type':'application/json'}})}));const host=document.createElement('div');document.body.append(host);const data:any={device_id:'device',default_room_id:'room-a',rooms,staff:[{id:'staff-1',name:'Teacher'}],children,unread_notes:0};await act(async()=>createRoot(host).render(<Presence data={data} roomId="room-a" staffId="staff-1" close={()=>{}} refresh={async()=>{}} notice={()=>{}}/>));await act(async()=>{([...host.querySelectorAll('button')].find(button=>button.textContent==='Arrive at centre')as HTMLButtonElement).click();await Promise.resolve()});expect(body.staff_id).toBe('staff-1');expect(body.action).toBe('arrive')});
});
