// @vitest-environment jsdom
import React from'react';import{act}from'react';import{createRoot}from'react-dom/client';import{afterEach,describe,expect,it,vi}from'vitest';import{Login}from'./account/Login';import PairTablet from'./classroom/Pair';
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
afterEach(()=>{document.body.innerHTML='';vi.unstubAllGlobals()});
const enter=(input:HTMLInputElement,value:string)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}))};
describe('fast entry forms',()=>{
  it('autofocuses login, preserves autocomplete, and submits from the form',async()=>{let request:any;vi.stubGlobal('fetch',vi.fn(async(_url:any,init:any)=>{request=init;return new Response('',{status:200})}));const host=document.createElement('div');document.body.append(host);let complete=0;await act(async()=>createRoot(host).render(<Login parent={false} onDone={()=>complete++}/>));const [identity,secret]=[...host.querySelectorAll('input')] as HTMLInputElement[];expect(document.activeElement).toBe(identity);expect(identity.autocomplete).toBe('username');expect(secret.autocomplete).toBe('current-password');expect(host.querySelector('button')?.hasAttribute('disabled')).toBe(true);await act(async()=>{enter(identity,'admin@test');enter(secret,'secret');host.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await Promise.resolve()});expect(JSON.parse(request.body)).toEqual({email:'admin@test',password:'secret'});expect(complete).toBe(1)});
  it('masks parent PIN and keeps pairing challenge numeric, focused and incomplete-disabled',async()=>{const loginHost=document.createElement('div');document.body.append(loginHost);await act(async()=>createRoot(loginHost).render(<Login parent onDone={()=>{}}/>));const parentInputs=[...loginHost.querySelectorAll('input')] as HTMLInputElement[];expect(parentInputs[1].type).toBe('password');const pairHost=document.createElement('div');document.body.append(pairHost);await act(async()=>createRoot(pairHost).render(<PairTablet/>));const challenge=pairHost.querySelector('input[inputmode="numeric"]') as HTMLInputElement;expect(document.activeElement).toBe(challenge);await act(async()=>enter(challenge,'a1b2'));expect(challenge.value).toBe('12');expect(pairHost.querySelector('button')?.hasAttribute('disabled')).toBe(true)});
});
