const DB='essentials-marked',OUTBOX='outbox',DRAFTS='drafts',SNAPSHOTS='snapshots';
export type SubmitFailure={message:string;status?:number;retryable:boolean;sessionExpired?:boolean};
export function sanitizeForLocalStorage(value:any):any{if(Array.isArray(value))return value.map(sanitizeForLocalStorage);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>!/pin|password|token/i.test(key)).map(([key,item])=>[key,sanitizeForLocalStorage(item)]));return value}
const scrub=sanitizeForLocalStorage;
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,3);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(OUTBOX))request.result.createObjectStore(OUTBOX,{keyPath:'client_id'});if(!request.result.objectStoreNames.contains(DRAFTS))request.result.createObjectStore(DRAFTS,{keyPath:'id'});if(!request.result.objectStoreNames.contains(SNAPSHOTS))request.result.createObjectStore(SNAPSHOTS,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function tx(store:string,mode:IDBTransactionMode,fn:(value:IDBObjectStore)=>IDBRequest){const database=await open();return new Promise<any>((resolve,reject)=>{const request=fn(database.transaction(store,mode).objectStore(store));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function queueItem(item:any){await save(item);globalThis.dispatchEvent?.(new Event('outbox-change'))}
export const queued=()=>tx(OUTBOX,'readonly',store=>store.getAll());export const save=(item:any)=>tx(OUTBOX,'readwrite',store=>store.put(scrub(item)));export const remove=(id:string)=>tx(OUTBOX,'readwrite',store=>store.delete(id));
export const saveDraft=(id:string,value:any)=>tx(DRAFTS,'readwrite',store=>store.put({id,updatedAt:Date.now(),value:scrub(value)}));export const loadDraft=(id:string)=>tx(DRAFTS,'readonly',store=>store.get(id));export const removeDraft=(id:string)=>tx(DRAFTS,'readwrite',store=>store.delete(id));export const listDrafts=async(prefix='')=>(await tx(DRAFTS,'readonly',store=>store.getAll())).filter((item:any)=>item.id.startsWith(prefix));
export const saveSnapshot=(id:string,value:any)=>tx(SNAPSHOTS,'readwrite',store=>store.put({id,updatedAt:Date.now(),value:scrub(value)}));export const loadSnapshot=(id:string)=>tx(SNAPSHOTS,'readonly',store=>store.get(id));
async function submit(path:string,safe:any,queuedItem:any,message:string,retryableStatuses=[502,503,504]){try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(safe)});if(response.ok)return{queued:false};const body=await response.json().catch(()=>({}));const error:SubmitFailure={message:body.detail||message,status:response.status,retryable:retryableStatuses.includes(response.status),sessionExpired:response.status===401};if(error.retryable){await queueItem(queuedItem);return{queued:true}}throw error}catch(error){if((error as SubmitFailure).status)throw error;if(!navigator.onLine||error instanceof TypeError){await queueItem(queuedItem);return{queued:true}}throw error}}
export async function submitOrdinary(item:any){const safe=scrub(item);return submit('/api/classroom/events',safe,safe,'Could not record this item.')}
export async function submitFoodBatch(item:any){const safe=scrub(item);return submit('/api/classroom/food-batch',safe,{client_id:item.client_operation_id,kind:'food_batch',payload:safe},'Could not record this food batch.',[500,502,503,504])}
export const outboxDelivery=(item:any)=>item.kind==='food_batch'?{path:'/api/classroom/food-batch',payload:item.payload}:{path:'/api/classroom/events',payload:item};
export async function sync(){let attention=0,unreachable=false;const items=await queued();if(!items.length){try{const response=await fetch('/api/health',{cache:'no-store'});unreachable=!response.ok}catch{unreachable=true}}for(const item of items){const{path,payload}=outboxDelivery(item);try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(response.ok)await remove(item.client_id);else if(!([502,503,504].includes(response.status)||(item.kind==='food_batch'&&response.status===500))){attention++;await tx(OUTBOX,'readwrite',store=>store.put({...item,needsAttention:true,error:`Server rejected (${response.status})`}))}else unreachable=true}catch{unreachable=true;break}}return{pending:(await queued()).length,needsAttention:attention,unreachable}}
