const DB='essentials-marked'; const OUTBOX='outbox'; const DRAFTS='drafts';
export type SubmitFailure={message:string; status?:number; retryable:boolean; sessionExpired?:boolean};
export function sanitizeForLocalStorage(value:any):any{if(Array.isArray(value))return value.map(sanitizeForLocalStorage);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!/pin|password|token/i.test(k)).map(([k,v])=>[k,sanitizeForLocalStorage(v)]));return value}
const scrub=sanitizeForLocalStorage;
function open():Promise<IDBDatabase>{return new Promise((ok,bad)=>{const r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(OUTBOX))r.result.createObjectStore(OUTBOX,{keyPath:'client_id'});if(!r.result.objectStoreNames.contains(DRAFTS))r.result.createObjectStore(DRAFTS,{keyPath:'id'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
async function tx(store:string,mode:IDBTransactionMode,fn:(s:IDBObjectStore)=>IDBRequest){const d=await open();return new Promise<any>((ok,bad)=>{const r=fn(d.transaction(store,mode).objectStore(store));r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
export const queued=()=>tx(OUTBOX,'readonly',s=>s.getAll()); export const save=(item:any)=>tx(OUTBOX,'readwrite',s=>s.put(scrub(item))); export const remove=(id:string)=>tx(OUTBOX,'readwrite',s=>s.delete(id));
export const saveDraft=(id:string,value:any)=>tx(DRAFTS,'readwrite',s=>s.put({id,updatedAt:Date.now(),value:scrub(value)})); export const loadDraft=(id:string)=>tx(DRAFTS,'readonly',s=>s.get(id));
export async function submitOrdinary(item:any){const safe=scrub(item);try{const r=await fetch('/api/classroom/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(safe)});if(r.ok)return {queued:false};const b=await r.json().catch(()=>({}));const e:SubmitFailure={message:b.detail||'Could not record this item.',status:r.status,retryable:[502,503,504].includes(r.status),sessionExpired:r.status===401};if(e.retryable){await save(safe);return {queued:true}}throw e}catch(e){if((e as SubmitFailure).status)throw e;if(!navigator.onLine||e instanceof TypeError){await save(safe);return {queued:true}}throw e}}
export async function sync(){let attention=0;for(const item of await queued()){try{const r=await fetch('/api/classroom/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});if(r.ok)await remove(item.client_id);else if(![502,503,504].includes(r.status)){attention++;await tx(OUTBOX,'readwrite',s=>s.put({...item,needsAttention:true,error:`Server rejected (${r.status})`}))}}catch{break}}return {pending:(await queued()).length,needsAttention:attention}}
