// @vitest-environment jsdom
import React,{useState}from'react';
import{act}from'react';
import{createRoot,Root}from'react-dom/client';
import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';
import{classroomUrl,RoomsManager,SafetyChecks}from'./admin/AdminConsole';
import Classroom,{resolveInitialRoom}from'./classroom/Classroom';
import{BodyAreaMap,readableBodyAreas}from'./classroom/BodyAreaMap';
import{Incident}from'./classroom/Incident';
import{ClearableSearch}from'./ui/ClearableSearch';

const offline=vi.hoisted(()=>({listDrafts:vi.fn(),removeDraft:vi.fn(),saveDraft:vi.fn(),saveSnapshot:vi.fn(),loadSnapshot:vi.fn(),sync:vi.fn()}));
vi.mock('./offline',async importOriginal=>({...await importOriginal<typeof import('./offline')>(),...offline}));

(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
class FakeEventSource{addEventListener(){}close(){}}
const json=(value:any)=>new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});
const input=(element:HTMLInputElement|HTMLTextAreaElement,value:string)=>{Object.getOwnPropertyDescriptor(element instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}))};
let roots:Root[]=[];
async function render(node:React.ReactNode){const host=document.createElement('div');document.body.append(host);const root=createRoot(host);roots.push(root);await act(async()=>{root.render(node);await Promise.resolve();await Promise.resolve()});return host}

beforeEach(()=>{offline.listDrafts.mockResolvedValue([]);offline.removeDraft.mockResolvedValue(undefined);offline.saveDraft.mockResolvedValue(undefined);offline.saveSnapshot.mockResolvedValue(undefined);offline.loadSnapshot.mockResolvedValue(undefined);offline.sync.mockResolvedValue({pending:0,needsAttention:0,unreachable:false});vi.stubGlobal('EventSource',FakeEventSource as any);localStorage.clear();history.replaceState({},'', '/');});
afterEach(async()=>{await act(async()=>roots.splice(0).forEach(root=>root.unmount()));document.body.innerHTML='';vi.clearAllMocks();vi.unstubAllGlobals();vi.useRealTimers()});

describe('0.2.3 navigation and shared search',()=>{
  it('uses an encoded Classroom URL and the required explicit, remembered, Device, first fallback order',()=>{
    const data:any={rooms:[{id:'Kōwhai / 1'},{id:'rimu'},{id:'device'}],default_room_id:'device'};
    expect(classroomUrl('Kōwhai / 1')).toBe('/classroom?room=K%C5%8Dwhai%20%2F%201');
    expect(classroomUrl('rimu')).toBe('/classroom?room=rimu');
    expect(resolveInitialRoom(data,'rimu','Kōwhai / 1')).toBe('rimu');
    expect(resolveInitialRoom(data,'missing','Kōwhai / 1')).toBe('Kōwhai / 1');
    expect(resolveInitialRoom(data,'missing','missing')).toBe('device');
    expect(resolveInitialRoom({...data,default_room_id:'missing'},null,null)).toBe('Kōwhai / 1');
  });

  it('consumes a valid explicit room and renders a 403 mode mismatch instead of redirecting to Attendance',async()=>{
    const bootstrap:any={device_id:'d',default_room_id:'device',rooms:[{id:'explicit',name:'Explicit',accent:'#123456',icon:'🌿'},{id:'device',name:'Device',accent:'#654321',icon:'🌳'}],staff:[{id:'s',name:'Sarah'}],children:[],unread_notes:0,centre:{display_name:'Demo'}};
    history.replaceState({},'', '/classroom?room=explicit');
    vi.stubGlobal('fetch',vi.fn(async(url:any)=>String(url).includes('bootstrap')?json(bootstrap):String(url).includes('sleep-status')?json({sessions:[]}):json([])));
    const replaced=vi.spyOn(history,'replaceState');const host=await render(<Classroom/>);expect(host.textContent).toContain('Explicit');expect(localStorage.getItem('classroom-room')).toBe('explicit');expect(replaced.mock.calls.some(call=>String(call[2])==='/classroom')).toBe(true);
    await act(async()=>roots.pop()!.unmount());host.remove();
    vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({detail:'Classroom Device required'}),{status:403,headers:{'Content-Type':'application/json'}})));
    const denied=await render(<Classroom/>);expect(denied.textContent).toContain('Classroom isn’t available on this browser');expect(denied.textContent).toContain('paired as a Child sign-in tablet');expect(denied.textContent).toContain('Open Child sign-in');expect(location.pathname).toBe('/classroom');
  });

  it('renders exactly one controlled, non-native clear control with a shared large hit target',async()=>{
    function Example(){const[value,setValue]=useState('');return <form><ClearableSearch label="Search records" value={value} onChange={setValue}/></form>}
    const host=await render(<Example/>),field=host.querySelector('input')!;expect(field.type).toBe('text');expect(field.getAttribute('role')).toBe('searchbox');expect(host.querySelectorAll('[aria-label="Clear search"]')).toHaveLength(0);await act(async()=>input(field,'Mila'));const clears=host.querySelectorAll('[aria-label="Clear search"]');expect(clears).toHaveLength(1);const clear=clears[0]as HTMLButtonElement;expect(clear.type).toBe('button');expect(clear.className).toContain('search-clear');field.focus();await act(async()=>clear.click());expect(field.value).toBe('');expect(document.activeElement).toBe(field);
  });
});

describe('0.2.3 Room and Safety management',()=>{
  it('keeps the selected Room editor outside the stable Room-card grid',async()=>{
    const rooms=[{id:'kowhai',name:'Kōwhai',icon:'🌿',accent:'#176B5B',present_count:2,enrolled_count:5},{id:'rimu',name:'Rimu',icon:'🌳',accent:'#225544',present_count:1,enrolled_count:4}];
    const host=await render(<RoomsManager data={{rooms}} reload={async()=>{}} notice={()=>{}}/>),grid=host.querySelector('.room-card-grid')!;expect(grid.querySelectorAll('.room-card')).toHaveLength(2);expect(grid.querySelector('.room-editor-section')).toBeNull();await act(async()=>([...grid.querySelectorAll('button')].find(button=>button.textContent?.includes('Kōwhai'))as HTMLButtonElement).click());const editor=host.querySelector('.room-editor-section')!;expect(editor.textContent).toContain('Edit Kōwhai');expect(grid.contains(editor)).toBe(false);expect(grid.querySelectorAll('.room-card')).toHaveLength(2);
  });

  it('allows any unchecked Safety Room, returns to the chooser, and reveals completion only when all are checked',async()=>{
    const room=(id:string,checked_at:string|null)=>({room_id:id,room_name:id==='a'?'Harakeke':'Rimu',expected_count:id==='a'?2:3,observed_count:checked_at?(id==='a'?2:3):null,expected_children:[],checked_at,match:checked_at?true:null,note:null});
    const initial:any={id:'check',status:'open',staff_id:'s',checker:'Sarah',started_at:'2026-09-12T00:00:00Z',completed_at:null,checked_count:1,room_count:2,has_mismatch:false,reauth_required:false,rooms:[room('a','2026-09-12T00:05:00Z'),room('b',null)]};
    const finished={...initial,checked_count:2,rooms:[room('a','2026-09-12T00:05:00Z'),room('b','2026-09-12T00:06:00Z')]};let latest=initial;const posts:any[]=[];
    vi.stubGlobal('fetch',vi.fn(async(_url:any,init:any={})=>{if(init.method==='POST'){posts.push(JSON.parse(init.body));latest=finished;return json(finished)}return json([latest])}));
    const host=await render(<SafetyChecks data={{centre:{timezone:'Pacific/Auckland'},staff:[]}} notice={()=>{}}/>);const checked=[...host.querySelectorAll('.safety-room-chooser button')].find(button=>button.textContent?.includes('Harakeke'))as HTMLButtonElement;expect(checked.disabled).toBe(true);expect(host.querySelector('.reauth-pin')).toBeNull();expect(host.textContent).not.toContain('Complete safety check');await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent?.includes('Rimu'))as HTMLButtonElement).click());expect((host.querySelector('[aria-label="Observed count"]')as HTMLInputElement).value).toBe('3');await act(async()=>{([...host.querySelectorAll('button')].find(button=>button.textContent==='Confirm count')as HTMLButtonElement).click();await Promise.resolve();await Promise.resolve()});expect(posts[0].expected_count).toBe(3);expect(host.querySelector('.safety-room')).toBeNull();expect(host.textContent).toContain('Complete safety check');
  });

  it('shows the original checker PIN only when the server requires reauthentication',async()=>{
    const check:any={id:'check',status:'open',staff_id:'s',checker:'Sarah',started_at:'2026-09-12T00:00:00Z',checked_count:0,room_count:1,has_mismatch:false,reauth_required:true,rooms:[{room_id:'a',room_name:'Harakeke',expected_count:2,expected_children:[],checked_at:null}]};vi.stubGlobal('fetch',vi.fn(async()=>json([check])));const host=await render(<SafetyChecks data={{centre:{timezone:'Pacific/Auckland'},staff:[]}} notice={()=>{}}/>);await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent?.includes('Harakeke'))as HTMLButtonElement).click());expect(host.querySelector('.reauth-pin input')).toBeTruthy();expect(([...host.querySelectorAll('button')].find(button=>button.textContent==='Confirm count')as HTMLButtonElement).disabled).toBe(true);
  });

  it('recovers when a selected fresh check crosses the reauthentication threshold',async()=>{
    const room={room_id:'a',room_name:'Harakeke',expected_count:2,observed_count:null,expected_children:[],checked_at:null,match:null,note:null};const fresh:any={id:'check',status:'open',staff_id:'s',checker:'Sarah',started_at:'2026-09-12T00:00:00Z',checked_count:0,room_count:1,has_mismatch:false,reauth_required:false,rooms:[room]};const aged={...fresh,reauth_required:true};let attempts=0;const posts:any[]=[];
    vi.stubGlobal('fetch',vi.fn(async(url:any,init:any={})=>{const path=String(url);if(init.method==='POST'){posts.push(JSON.parse(init.body));attempts+=1;if(attempts===1)return new Response(JSON.stringify({detail:'Re-enter the checker PIN to continue this older safety check'}),{status:403,headers:{'Content-Type':'application/json'}});return json({...aged,checked_count:1,rooms:[{...room,observed_count:1,checked_at:'2026-09-12T00:31:00Z',match:false,note:'One child with a teacher'}]})}if(path.endsWith('/safety-checks/check'))return json(aged);return json([attempts>1?aged:fresh])}));
    const host=await render(<SafetyChecks data={{centre:{timezone:'Pacific/Auckland'},staff:[]}} notice={()=>{}}/>);await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent?.includes('Harakeke'))as HTMLButtonElement).click());expect(host.querySelector('.reauth-pin')).toBeNull();await act(async()=>(host.querySelector('[aria-label="Decrease observed count"]')as HTMLButtonElement).click());await act(async()=>input(host.querySelector('textarea')!,'One child with a teacher'));await act(async()=>{([...host.querySelectorAll('button')].find(button=>button.textContent==='Confirm mismatch')as HTMLButtonElement).click();await Promise.resolve();await Promise.resolve();await Promise.resolve()});expect(host.querySelector('.reauth-pin input')).toBeTruthy();expect(host.querySelector('.safety-room')?.textContent).toContain('Harakeke');expect((host.querySelector('[aria-label="Observed count"]')as HTMLInputElement).value).toBe('1');expect((host.querySelector('textarea')as HTMLTextAreaElement).value).toBe('One child with a teacher');const reauth=host.querySelector('.reauth-pin input')as HTMLInputElement;await act(async()=>input(reauth,'1234'));await act(async()=>{([...host.querySelectorAll('button')].find(button=>button.textContent==='Confirm mismatch')as HTMLButtonElement).click();await Promise.resolve();await Promise.resolve()});expect(posts).toHaveLength(2);expect(posts[1]).toMatchObject({staff_pin:'1234',expected_count:2,observed_count:1,note:'One child with a teacher'});
  });
});

describe('0.2.3 Incident workflow',()=>{
  it('toggles accessible front/back body regions without changing stored identifiers',async()=>{
    function Example(){const[value,setValue]=useState<string[]>([]);return <><BodyAreaMap value={value} onChange={setValue}/><output>{value.join('|')}</output></>}
    const host=await render(<Example/>);expect(host.textContent).toContain('Front');expect(host.textContent).toContain('Back');const chest=host.querySelector('[data-area="chest"]')!;await act(async()=>chest.dispatchEvent(new MouseEvent('click',{bubbles:true})));expect(chest.getAttribute('aria-pressed')).toBe('true');await act(async()=>chest.dispatchEvent(new MouseEvent('click',{bubbles:true})));expect(chest.getAttribute('aria-pressed')).toBe('false');const left=host.querySelector('[data-area="left_arm"]')!,right=host.querySelector('[data-area="right_leg"]')!;await act(async()=>left.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true})));await act(async()=>right.dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true})));expect(host.querySelector('output')?.textContent).toBe('left_arm|right_leg');expect(left.getAttribute('aria-pressed')).toBe('true');await act(async()=>(host.querySelector('.body-other')as HTMLButtonElement).click());expect(host.querySelector('output')?.textContent).toContain('other');expect(readableBodyAreas(['left_arm','right_leg'])).toBe('Left arm, Right leg');
  });

  it('confirms meaningful Clear information, keeps data on cancel, cleans local/server drafts, resets, and stays open',async()=>{
    const draft={client_draft_id:'incident-draft-one',finalise_operation_id:'incident-final-one',incident_id:'server-one',selected:['c'],effective:'',implicit_effective_at:'2026-09-12T00:00:00Z',environment:'indoor',location:'Playground',incident_type:'Bump',other_child_id:'',skin_broken:false,description:'Details',body_areas:['left_arm'],actions:[{time:'',description:''}]};offline.listDrafts.mockResolvedValue([{id:draft.client_draft_id,value:draft}]);const calls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(url:any,init:any={})=>{calls.push(`${init.method||'GET'} ${String(url)}`);return json([])}));const refresh=vi.fn(async()=>{});const host=await render(<Incident data={{device_id:'d',default_room_id:'r',rooms:[{id:'r',name:'Rimu',icon:'🌳',accent:'#123456'}],staff:[],children:[{id:'c',first_name:'Mila',last_name:'Chen',room_id:'r'}],unread_notes:0}} roomId="r" staffId="s" close={vi.fn()} refresh={refresh} notice={()=>{}}/>);await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent?.includes('Mila · Bump'))as HTMLButtonElement).click());expect((host.querySelector('input[value="Bump"]')as HTMLInputElement).value).toBe('Bump');await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent==='Clear information')as HTMLButtonElement).click());expect(host.textContent).toContain('Clear incident information?');await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent==='Keep information')as HTMLButtonElement).click());expect(host.querySelector('input[value="Bump"]')).toBeTruthy();await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent==='Clear information')as HTMLButtonElement).click());const dialog=host.querySelector('[role="dialog"]')!;await act(async()=>{([...dialog.querySelectorAll('button')].find(button=>button.textContent==='Clear information')as HTMLButtonElement).click();await Promise.resolve();await Promise.resolve()});expect(offline.removeDraft).toHaveBeenCalledWith('incident-draft-one');expect(calls).toContain('DELETE /api/classroom/incidents/drafts/server-one');expect(host.textContent).toContain('Incident / Injury');expect(host.textContent).not.toContain('Review incident');expect((host.querySelector('input[value=""]')as HTMLInputElement)).toBeTruthy();expect(refresh).toHaveBeenCalled();
  });

  it('makes an explicit clear win over a pending delayed Incident autosave',async()=>{
    vi.useFakeTimers();const draft={client_draft_id:'incident-draft-race',finalise_operation_id:'incident-final-race',incident_id:'server-race',selected:['c'],effective:'',implicit_effective_at:'2026-09-12T00:00:00Z',environment:'indoor',location:'Playground',incident_type:'Bump',other_child_id:'',skin_broken:false,description:'Original',body_areas:[],actions:[{time:'',description:''}]};offline.listDrafts.mockResolvedValue([{id:draft.client_draft_id,value:draft}]);const requests:{method:string;url:string}[]=[];vi.stubGlobal('fetch',vi.fn(async(url:any,init:any={})=>{requests.push({method:init.method||'GET',url:String(url)});return json([])}));const refresh=vi.fn(async()=>{}),close=vi.fn();const host=await render(<Incident data={{device_id:'d',default_room_id:'r',rooms:[{id:'r',name:'Rimu',icon:'🌳',accent:'#123456'}],staff:[],children:[{id:'c',first_name:'Mila',last_name:'Chen',room_id:'r'}],unread_notes:0}} roomId="r" staffId="s" close={close} refresh={refresh} notice={()=>{}}/>);await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent?.includes('Mila · Bump'))as HTMLButtonElement).click());const description=[...host.querySelectorAll('label')].find(label=>label.textContent?.startsWith('description'))!.querySelector('input')!;await act(async()=>input(description,'Edited immediately before clear'));await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent==='Clear information')as HTMLButtonElement).click());const dialog=host.querySelector('[role="dialog"]')!;await act(async()=>{([...dialog.querySelectorAll('button')].find(button=>button.textContent==='Clear information')as HTMLButtonElement).click();await Promise.resolve();await Promise.resolve();await Promise.resolve()});await act(async()=>vi.runAllTimersAsync());expect(requests.filter(request=>request.method==='POST'&&request.url.endsWith('/classroom/incidents'))).toHaveLength(0);expect(requests).toContainEqual({method:'DELETE',url:'/api/classroom/incidents/drafts/server-race'});expect(offline.removeDraft).toHaveBeenCalledWith('incident-draft-race');expect(host.textContent).toContain('Incident / Injury');const freshDescription=[...host.querySelectorAll('label')].find(label=>label.textContent?.startsWith('description'))!.querySelector('input')as HTMLInputElement;expect(freshDescription.value).toBe('');expect(close).not.toHaveBeenCalled();expect(refresh).toHaveBeenCalled();
  });

  it('deletes the server ID created by an in-flight first autosave before clearing locally',async()=>{
    vi.useFakeTimers();let resolveAutosave:(response:Response)=>void=()=>{};const autosaveResponse=new Promise<Response>(resolve=>{resolveAutosave=resolve});const events:string[]=[];offline.removeDraft.mockImplementation(async(id:string)=>{events.push(`remove:${id}`)});vi.stubGlobal('fetch',vi.fn(async(url:any,init:any={})=>{const path=String(url);if(init.method==='POST'&&path.endsWith('/classroom/incidents')){events.push('post:start');return autosaveResponse}if(init.method==='DELETE'){events.push(`delete:${path}`);return json({})}return json([])}));const refresh=vi.fn(async()=>{}),close=vi.fn();const host=await render(<Incident data={{device_id:'d',default_room_id:'r',rooms:[{id:'r',name:'Rimu',icon:'🌳',accent:'#123456'}],staff:[],children:[{id:'c',first_name:'Mila',last_name:'Chen',room_id:'r',present:true}],unread_notes:0}} roomId="r" staffId="s" close={close} refresh={refresh} notice={()=>{}}/>);await act(async()=>{([...host.querySelectorAll('button')].find(button=>button.textContent?.includes('Mila Chen'))as HTMLButtonElement).click()});const type=[...host.querySelectorAll('label')].find(label=>label.textContent?.startsWith('incident type'))!.querySelector('input')!;await act(async()=>input(type,'Bump'));await act(async()=>{vi.advanceTimersByTime(700);await Promise.resolve();await Promise.resolve()});expect(events).toEqual(['post:start']);await act(async()=>([...host.querySelectorAll('button')].find(button=>button.textContent==='Clear information')as HTMLButtonElement).click());const dialog=host.querySelector('[role="dialog"]')!;await act(async()=>{([...dialog.querySelectorAll('button')].find(button=>button.textContent==='Clear information')as HTMLButtonElement).click();await Promise.resolve()});expect(events).toEqual(['post:start']);expect(offline.removeDraft).not.toHaveBeenCalled();await act(async()=>{resolveAutosave(json({id:'created-draft'}));await Promise.resolve();await Promise.resolve();await Promise.resolve();await Promise.resolve()});expect(events.slice(0,2)).toEqual(['post:start','delete:/api/classroom/incidents/drafts/created-draft']);expect(events[2]).toMatch(/^remove:incident-draft-/);await act(async()=>vi.runAllTimersAsync());expect(events.filter(event=>event==='post:start')).toHaveLength(1);expect((type as HTMLInputElement).value).toBe('');expect(close).not.toHaveBeenCalled();expect(refresh).toHaveBeenCalled();
  });
});
